### ISSUE TITLE
`fatal error: julia_gcext.h: No such file or directory` in julia nightly

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/GAP.jl#1016]
I suspect this is due to https://github.com/JuliaLang/julia/pull/54238.

**Comment by fingolfin** [comment]
Indeed *sigh*

**Comment by lgoettgens** [comment]
I'm already working on a trivial fix in GAP.

**Comment by fingolfin** [comment]
I actually would prefer to have this reverted in Julia... but it won't hurt to pursue this on both fronts.

But I am concerned about the removal `PUBLIC_HEADERS += $(addprefix $(SRCDIR)/,julia_gcext.h)` as I think that header may be missing in the downloadable Julia releases (but I did not check that)

**Comment by lgoettgens** [comment]
There is indeed already a PR to revert it in julia: https://github.com/JuliaLang/julia/pull/54864

**Comment by ThomasBreuer** [comment]
As far as I understand, the revert is due to some failures inside Julia.
Thus I expect that sooner or later they will move the files as proposed.

**Comment by lgoettgens** [comment]
Resolved via https://github.com/JuliaLang/julia/pull/54864. The failures should go away with the next nightly version
