### ISSUE TITLE
Warning "The Julia package 'Downloads' cannot be loaded" when starting GAP.jl in CI

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#1040]
This is printed by `JuliaImportPackage`.

That in turn is called by GAP's `PackageManage` which has a `Download.g` file containing this:
```
if IsBound(Julia) and JuliaImportPackage("Downloads") = true then
```

**Comment by fingolfin** [comment]
Perhaps turning up the `PackageLoadingMessage` to `PACKAGE_DEBUG` will give some insight.

Also perhaps we should take advantage of that code in PackageManager to remove the hack where we patch PackageManager in `src/packages.jl`, function `init_packagemanager`.

**Comment by ThomasBreuer** [comment]
Thanks for the hint about the `JuliaImportPackage` call in a GAP package.
This explains why a `git grep JuliaImportPackage` in GAP.jl did not answer the question who calls this function with `"Downloads"`.

**Comment by thofma** [comment]
I also saw this locally:
```
Precompiling project...
  11 dependencies successfully precompiled in 76 seconds. 77 already precompiled. 1 skipped during auto due to previous errors.
  1 dependency had output during precompilation:
┌ Hecke → GAPExt
│  #I  The Julia package 'Downloads' cannot be loaded.
└
```
