### ISSUE TITLE
Naming conventions: JuliaGetGlobalVariable vs. JuliaFunction

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#175]
I was wondering why it is `JuliaGetGlobalVariable` versus `JuliaFunction`, `JuliaModule`, `JuliaSymbol`, ... Shouldn't it be just `JuliaGlobalVariable`?

**Comment by sebasguts** [comment]
I guess you are right here :). Will provide a PR.

**Comment by fingolfin** [comment]
@ThomasBreuer should we just get rid of `JuliaGetGlobalVariable`? Is there any situation one would want or need to use it instead of writing `Julia.VAR` or `Julia.MODULE.VAR` (or `Julia.MODULE1.MODULE2.VAR` etc. etc.) ?
