### ISSUE TITLE
Rename repository to GAP.jl ?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#208]
Thoughs? @ThomasBreuer @sebasguts ?

**Comment by sebasguts** [comment]
I am all for it.

**Comment by sebasguts** [comment]
@ThomasBreuer What is your opinion on this?

**Comment by ThomasBreuer** [comment]
As I had myself raised the question to rename the repository
(in a discussion about a pull request), I do of course agree.

**Comment by sebasguts** [comment]
Okay :) Then we will do this once we fixed those travis problems ...
