### ISSUE TITLE
problem with tests for build #620 in Julia nightly

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#223]
One out of four Travis tests for build #620 fails due to a segmentation fault when `JuliaInterface/tst/calls.tst` is executed.
This happens with Julia nightly but not with Julia 1.1.
It seems to be reproducible, as I got notifications about the failure yesterday and today.

**Comment by sebasguts** [comment]
I see. It is weird that this only happens for one of the GAP's, and not both. This might be the case due to travis caches.

I will investigate that failure.

**Comment by sebasguts** [comment]
I am sorry, but I was not able to reproduce this failure on my machine alone. It is constantly happening in Travis for both builds with nightly Julia now, so I guess we should put more time in it.

**Comment by sebasguts** [comment]
Actually, this was a bit too hastly. I did not look at the error messages. The current failures are all GC bugs, so maybe there is something new broken in there?

**Comment by sebasguts** [comment]
The problem disappeared, to we can close this for now...
