### ISSUE TITLE
I can not install GAP.jl in Mac.10.13.4

### ISSUE THREAD

**Issue by gangchern** [oscar-system/GAP.jl#230]
] add https://github.com/oscar-system/GAP.jl
┌ Error: Error building `GAP`: 
│ Cloning into 'gap'...
│ + autoconf -Wall -f
│ ./autogen.sh: line 5: autoconf: command not found
│ ERROR: LoadError: failed process: Process(`./autogen.sh`, ProcessExited(127)) [127]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run(::Cmd) at ./process.jl:724
│  [5] top-level scope at /Users/gangchen/.julia/packages/GAP/8uVqF/deps/build.jl:27
│  [6] include at ./boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1038
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] include(::String) at ./client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at /Users/gangchen/.julia/packages/GAP/8uVqF/deps/build.jl:20
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by sebasguts** [comment]
Hey, thanks fo using `GAP.jl`. It looks like your Mac is missing autotools. If you have homebrew, you can do
```
brew install autoconf
```
and the installation should succeed. Maybe @fingolfin can also say something about this?

**Comment by fingolfin** [comment]
Sorry for the hassle, but that's an artifact of GAP.jl still being very much under heavy development.

Probably best to install *all* packages suggested by the GAP build instructions. So:

 * using Homebrew: `brew install autoconf libtool gmp readline`
 * using Fink: `fink install autoconf2.6 libtool2 gmp5 readline7`
 * using MacPorts: `port install autoconf libtool gmp readline`

That said, only autoconf & libtool are really required. And only because we are currently using a development version of GAP for GAP.jl. Once GAP 4.11 is out, we should switch to installing release versions of GAP, which don't require autoconf and libtool.

**Comment by gangchern** [comment]
Hi, max
Thanks for your quick reply. Right now I have installed the following packages 
> 
> autoconf libtool gmp readline
Some errors have really solved. But there is still errors. The report is as following. Could you tell me how to fix these errors? Thanks a lot.
Error: Error building `GAP`, showing the last 100 of log: 
│ config.status: creating gen/config.h
│ config.status: executing gen/stamp-h commands
│ config.status: executing libtool commands
│ GAP_VERSION = 4.10dev-1998-g7ab3b05
│     * new C compiler flags
│     * new preprocessor flags
│     * new C++ compiler flags
│    SED     src/gap_version.c.in => gen/gap_version.c
│     * new link flags
│     * new library flags
│     * new object list
│    C       src/blister.c => obj/src/blister.lo
│    C       src/bags.c => obj/src/bags.lo
│    C       src/ariths.c => obj/src/ariths.lo
│    C       src/bool.c => obj/src/bool.lo
│    C       src/c_oper1.c => obj/src/c_oper1.lo
│    C       src/c_type1.c => obj/src/c_type1.lo
│    C       src/calls.c => obj/src/calls.lo
│    C       src/code.c => obj/src/code.lo
│    CXX     src/collectors.cc => obj/src/collectors.lo
│    C       src/compiler.c => obj/src/compiler.lo
│    C       src/compstat.c => obj/src/compstat.lo
│    C       src/costab.c => obj/src/costab.lo
│    C       src/cyclotom.c => obj/src/cyclotom.lo
│    C       src/debug.c => obj/src/debug.lo
│    C       src/dt.c => obj/src/dt.lo
│    C       src/dteval.c => obj/src/dteval.lo
│    C       src/error.c => obj/src/error.lo
│    C       src/exprs.c => obj/src/exprs.lo
│    C       src/ffdata.c => obj/src/ffdata.lo
│    C       src/finfield.c => obj/src/finfield.lo
│    C       src/funcs.c => obj/src/funcs.lo
│    C       src/gap.c => obj/src/gap.lo
│    C       gen/gap_version.c => obj/gen/gap_version.lo
│    C       src/gvars.c => obj/src/gvars.lo
│    C       src/hookintrprtr.c => obj/src/hookintrprtr.lo
│    C       src/info.c => obj/src/info.lo
│    C       src/integer.c => obj/src/integer.lo
│    C       src/intfuncs.c => obj/src/intfuncs.lo
│    C       src/intrprtr.c => obj/src/intrprtr.lo
│    C       src/io.c => obj/src/io.lo
│    C       src/iostream.c => obj/src/iostream.lo
│    C       src/libgap-api.c => obj/src/libgap-api.lo
│    C       src/listfunc.c => obj/src/listfunc.lo
│    C       src/listoper.c => obj/src/listoper.lo
│    C       src/lists.c => obj/src/lists.lo
│    C       src/macfloat.c => obj/src/macfloat.lo
│    C       src/modules.c => obj/src/modules.lo
│    C       src/modules_builtin.c => obj/src/modules_builtin.lo
│    C       src/objcftl.c => obj/src/objcftl.lo
│    C       src/objects.c => obj/src/objects.lo
│    CXX     src/objfgelm.cc => obj/src/objfgelm.lo
│    CXX     src/objpcgel.cc => obj/src/objpcgel.lo
│    C       src/objset.c => obj/src/objset.lo
│    C       src/opers.c => obj/src/opers.lo
│    CXX     src/permutat.cc => obj/src/permutat.lo
│    C       src/plist.c => obj/src/plist.lo
│    CXX     src/pperm.cc => obj/src/pperm.lo
│    C       src/precord.c => obj/src/precord.lo
│    C       src/profile.c => obj/src/profile.lo
│    C       src/range.c => obj/src/range.lo
│    C       src/rational.c => obj/src/rational.lo
│    C       src/read.c => obj/src/read.lo
│    C       src/records.c => obj/src/records.lo
│    C       src/saveload.c => obj/src/saveload.lo
│    C       src/scanner.c => obj/src/scanner.lo
│    C       src/sctable.c => obj/src/sctable.lo
│    C       src/set.c => obj/src/set.lo
│    C       src/stats.c => obj/src/stats.lo
│    C       src/streams.c => obj/src/streams.lo
│    C       src/stringobj.c => obj/src/stringobj.lo
│    C       src/syntaxtree.c => obj/src/syntaxtree.lo
│    C       src/sysfiles.c => obj/src/sysfiles.lo
│    C       src/sysmem.c => obj/src/sysmem.lo
│    C       src/system.c => obj/src/system.lo
│    C       src/tietze.c => obj/src/tietze.lo
│    CXX     src/trans.cc => obj/src/trans.lo
│    C       src/vars.c => obj/src/vars.lo
│    C       src/vec8bit.c => obj/src/vec8bit.lo
│    C       src/vecffe.c => obj/src/vecffe.lo
│    C       src/vecgf2.c => obj/src/vecgf2.lo
│    C       src/vector.c => obj/src/vector.lo
│    C       src/weakptr.c => obj/src/weakptr.lo
│    C       src/julia_gc.c => obj/src/julia_gc.lo
│    LINK    gap
│    LINK    libgap.la
│ /bin/sh: wget: command not found
│ make: *** [bootstrap-pkg-full] Error 127
│ ERROR: LoadError: failed process: Process(`make bootstrap-pkg-full`, ProcessExited(2)) [2]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run(::Cmd) at ./process.jl:724
│  [5] top-level scope at /Users/gangchen/.julia/packages/GAP/8uVqF/deps/build.jl:32
│  [6] include at ./boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1038
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] include(::String) at ./client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at /Users/gangchen/.julia/packages/GAP/8uVqF/deps/build.jl:20
│ 
│ Full log at /Users/gangchen/.julia/packages/GAP/8uVqF/deps/build.log
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by fingolfin** [comment]
It seems you also need to `brew install wget`. Sorry for the hassle.

**Comment by sebasguts** [comment]
We will add this to the Readme for now :)

**Comment by gangchern** [comment]
Thanks a lot. It is really helpful

**Comment by fingolfin** [comment]
@sebasguts you never added `wget` to the README, did you?

We might also want to change GAP to work with curl instead of wget (as curl is arguably available on more systems), resp. in addition. See also here: https://github.com/gap-system/gap/issues/1866

**Comment by fingolfin** [comment]
We are not using wget anymore.
