### ISSUE TITLE
If GAP is the host, and Julia embedded, we should perhaps catch Julia's screen output (at least for errors)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#237]
Right now, running the `JuliaInterface` test suite from within GAP prints this:
```
...
testing: /home/travis/.julia/packages/GAP/95DX2/pkg/GAPJulia/JuliaInterface/ts\
t/JuliaToGAP.tst
     468 ms (432 ms GC) and 45.8KB allocated for JuliaToGAP.tst
testing: /home/travis/.julia/packages/GAP/95DX2/pkg/GAPJulia/JuliaInterface/ts\
t/adapter.tst
    1664 ms (316 ms GC) and 226KB allocated for adapter.tst
testing: /home/travis/.julia/packages/GAP/95DX2/pkg/GAPJulia/JuliaInterface/ts\
t/calls.tst
# line 239 of 296 (80%)WARNING: cfunction: return type of h0 does not match
# line 240 of 296 (81%)WARNING: cfunction: return type of h1 does not match
# line 241 of 296 (81%)WARNING: cfunction: return type of h2 does not match
# line 242 of 296 (81%)WARNING: cfunction: return type of h3 does not match
# line 243 of 296 (82%)WARNING: cfunction: return type of h4 does not match
# line 244 of 296 (82%)WARNING: cfunction: return type of h5 does not match
# line 245 of 296 (82%)WARNING: cfunction: return type of h6 does not match
...
```
These "WARNING: cfunction: return type of h6 does not match" messages are printed by Julia. I think we should catch them and add a way for the user to query these strings if desired; alternatively, we could turn the Julia error into a GAP error, by calling something like this pseudo code: `ErrorQuit("Julia run into an error: %s", juliaErrorOutput, 0)`

**Comment by fingolfin** [comment]
I guess this (partially?) duplicates issue #95

**Comment by ThomasBreuer** [comment]
@fingolfin Since this issue is still open:
Julia's screen output is interesting in general, not only in the case of error messages.
For example, the output of
```
gap> JuliaEvalString( "println( [1,2,3,4] )" );;
```
is shown on the screen but does not occur in a GAP logfile.
There should be a way to redirect all printed output (of GAP and Julia, in a GAP session and in a Julia session),
but where is the right place to force this behaviour?

(Can we expect that some of the problems described in #516 will disappear when all printed output gets redirected properly?)

**Comment by fingolfin** [comment]
Perhaps we can use `Base.redirect_stdout` and `Base.redirect_stderr` (and `Base.redirect_stdin`) for this?

Moreover, since these days (esp. with the GAP_jll PR #550) the plan kinda is to always start Julia first, then GAP, we should also look into redirecting GAP's input/output to Julia. (note that the two redirection directions are independent and we may need to have them both active at the same time, somehow. Hrm.

**Comment by fingolfin** [comment]
We dropped support for using GAP as a host last year
