### ISSUE TITLE
Get GAP to use the same GMP as Julia, Nemo, ...

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#254]
... by passing suitable build flags to it. That said, I don't even know if Nemo and Julia really use the same GMP right now? In any case, we should at least try to link against a foreign GMP, or even against our own GMP (built by GAP if it cannot find any "global" GMP installation).

**Comment by fingolfin** [comment]
Note that while this would be nice, I don't think there is a serious issue if we don't, as long as all copies of GMP are compiled with compatible (=default) settings.

**Comment by fieker** [comment]
On Wed, Jan 22, 2020 at 07:50:07AM -0800, Max Horn wrote:
> Note that while this would be nice, I don't think there is a serious issue if we don't, as long as all copies of GMP are compiled with compatible (=default) settings.
> 
... and initialized to use the same memory manager ...

**Comment by fingolfin** [comment]
That at least no issue: GAP largely avoids GMP allocation; the only ones are in kernel functions for temporary allocations but cannot escape.
