### ISSUE TITLE
Make GAPTypes.jl a dependency in the Project.toml

### ISSUE THREAD

**Issue by thofma** [oscar-system/GAP.jl#265]
Otherwise you get
```julia
julia> using GAP
Adding path /home/adsd/.julia/packages/GAP/aMcJN/gap/.libs to DL_LOAD_PATH
Panic in src/julia_gc.c:825: could not import GAPTypes module into Julia
```

**Comment by fingolfin** [comment]
This will be taken care of by PR #249 which will be merged soon.

**Comment by thofma** [comment]
Sorry, I did not see the PR.

**Comment by fingolfin** [comment]
Sure thing! I didn't mean to imply that you should have known about it (IMHO there is no reason for this -- I am not aware of most AbstractAlgebra PRs either). I just added the comment for reference.
