### ISSUE TITLE
GAP not starting when installed via GAP.jl

### ISSUE THREAD

**Issue by markuslh** [oscar-system/GAP.jl#277]
Setting: Ubuntu in WSL, the packages in `https://oscar.computeralgebra.de/install/` are all installed. `GAP.jl` is installed in Julia as dev-package.

GAP runs when called from Julia, however, I cannot get GAP to work from bash.

```
markus@XXX:~/.julia/dev/GAP$ ./gap.sh
ERROR: could not load library "/usr/lib/x86_64-linux-gnu/../bin/../lib/x86_64-linux-gnu/julia/sys.so"
/usr/lib/x86_64-linux-gnu/../bin/../lib/x86_64-linux-gnu/julia/sys.so: cannot open shared object file: No such file or directory
```

I get the same errors when calling the GAP-binary directly.

**Comment by fingolfin** [comment]
@markuslh huh, I never noticed this report before :-(.  So sorry, my apologies.

Is this still something that is relevant for you? I can't reproduce it. I'd need to know some more information, such as 
- the precise Ubuntu version
- which Julia version?
- where is Julia installed, (`type julia` should give that info)
- which GAP.jl version?
- how did you install GAP.jl? When you say "as dev-package", do you mean you used `] dev .` in a clone of GAP.jl? If so, why not just `] add GAP` instead? 

The message you post involves the path `/usr/lib/x86_64-linux-gnu/../bin/../lib/x86_64-linux-gnu/julia/sys.so` which simplifies to `/usr/lib/lib/x86_64-linux-gnu/julia/sys.so` which indeed looks suspiciously wrong. But w/o more info it's hard to say what's going on.
