### ISSUE TITLE
Converting list to tuple with gap_to_julia may not preserve length

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#278]
I am not sure whether this is a bug or a (mis-)feature, but while trying to understand the tuple conversion code, I noticed this:
```
julia> l = GAP.EvalString("[1,2,3,4]")
GAP: [ 1, 2, 3, 4 ]

julia> t = GAP.gap_to_julia(Tuple{Int64, Int64}, l)
(1, 2)
```

I think this should instead throw an error. So the tuple conversion function should check that the length of the input list and the desired output tuple type match. Then, it could also be simplified, I think, by iterating over the entries of the input GAP list directly, instead of first converting that to an Array via another call to `gap_to_julia`

**Comment by ThomasBreuer** [comment]
I agree that it should be regarded as an error when the two lengths are different.
(One gets a `BoundsError` when the list is *shorter* than the description of the Julia type.)
