### ISSUE TITLE
GAP's `-r` option and Julia's `.julia/config/startup.jl`

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#284]
(Perhaps this is related to issue #246.)

What is the reason for setting GAP's `-r` option in the call of `run_it`, in `GAP.jl/src/GAP.jl`?

The effect is that the user's `.gap` directory gets ignored when one calls `using GAP` from Julia.
Thus the file `.gap/gaprc` is not read, and the directory `GAPInfo.UserGapRoot` does not get added to `GAPInfo.RootPaths`.
The latter means that the packages in the `pkg` subdirectory of `GAPInfo.UserGapRoot` are not found automatically.

We could either remove the `-r` option from the call of `run_it`, or document this option.
(It is o.k. not to load packages, by the `-A` option. We should document also this option.)

The other way round, that is, when GAP starts Julia, Julia's `.julia/config/startup.jl` is not read.
Here it is not clear what a natural situation for reading this file would be, perhaps the time when GAP's `JuliaInterface` package gets loaded, because this marks the time when one can start using Julia (and not just its garbage collector).
Should `.julia/config/startup.jl` be read then or not?

**Comment by fingolfin** [comment]
@ThomasBreuer I can't think of a good reason why we pass `-r` by default. Nor why we pass `-m 1000m`. If you want to submit a PR to remove either, I'd merge it.

That said, it would probably be nice if there was some way for the user to tweak these options; at least adding additional GAP roots could be useful. Not sure what a good user interface for achieving this would be, though. Anyway I am guessing this is mostly useful for a few power users.

As for option `-A`: I think it makes sense to start with a clean slate here, if it didn't break the expectations of long-time GAP user's, I'd actually prefer if it was the default in regular GAP, too. If we remove `-r` then power users can still load their own default packages, I think?


As to `.julia/config/startup.jl`, I don't think we made a conscious decision not to load it, but rather   this is a side effect from us not doing something (or perhaps doing something wrong). It might be a good idea to first understand why this happens...
