### ISSUE TITLE
GAP.jl broken?

### ISSUE THREAD

**Issue by thofma** [oscar-system/GAP.jl#291]
Fresh julia installation.
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /tmp/new

(v1.2) pkg> add GAP
  Updating registry at `/tmp/new/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed GAPTypes ─ v1.0.0
 Installed GAP ────── v0.2.1
  Updating `/tmp/new/environments/v1.2/Project.toml`
  [c863536a] + GAP v0.2.1
  Updating `/tmp/new/environments/v1.2/Manifest.toml`
  [c863536a] + GAP v0.2.1
  [cd4130c4] + GAPTypes v1.0.0
  Building GAP → `/tmp/new/packages/GAP/JMFDD/deps/build.log`

julia> using GAP
[ Info: Precompiling GAP [c863536a-3901-11e9-33e7-d5cd0df7b904]
Adding path /tmp/new/packages/GAP/JMFDD/gap/.libs to DL_LOAD_PATH
Panic in src/julia_gc.c:756: GAPTypes.jl is not available
```
Fails also with the same error on julia 1.1. I am pretty sure this used to work.

**Comment by ThomasBreuer** [comment]
@thofma The problem arises because of a bug in https://github.com/gap-system/gap/pull/3669, in the GAP master branch.

**Comment by thofma** [comment]
Thanks. Any way to work around this? Is the GAP version in GAP.jl fixed or does it pull in the latest master branch of GAP?

**Comment by fingolfin** [comment]
I'll take care of this shortly. Thomas made me aware if this before, but I didn't get to it yesterday

**Comment by fingolfin** [comment]
The problem is a missing change on the GAP.jl side, plus a lack of proper integration testing in the GAP CI tests, which do have some minimal tests for the Julia integration, but do not test against GAP.jl yet. I'll look into that, too
