### ISSUE TITLE
Add upper bound to GAPTypes dependency

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#299]
On https://github.com/JuliaRegistries/General/pull/5422 we were told:

> The following dependencies do not have a compat entry that has an upper bound: GAPTypes

**Comment by ThomasBreuer** [comment]
Currently `GAPTypes.jl` has version `"1.0.0"`.
We could be very conservative in the sense that any change in `GAPTypes.jl` will likely be incompatible, and will require a new release of `GAP.jl`.
If I understand the documentation in `Pkg.jl` right then we can express this as follows.
```
[compat]
GAPTypes = "= 1.0.0"
```

**Comment by fredrikekre** [comment]
Bump for https://github.com/JuliaRegistries/General/pull/5422. I would recommend:
```
[compat]
GAPTypes = "1"
```
if you are following semantic versioning.
