### ISSUE TITLE
test failure for pull request #300

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#301]
The (first) failure at https://github.com/oscar-system/GAP.jl/pull/300/checks?check_run_id=322748382 looks strange.
My interpretation is that first GAP's `GAPToJulia` creates a nested array of the following structure.
```julia
julia> l = Any[ Any[ 1, 2 ], Any[ 3, 4 ] ]
2-element Array{Any,1}:
 Any[1, 2]
 Any[3, 4]
```
Then Julia's `hcat` turns the nested array into a 2-dimensional array.
```julia
julia> hcat( l... )
2×2 Array{Int64,2}:
 1  3
 2  4

julia> Base.repr( hcat( l... ) )
"[1 3; 2 4]"
```
In the seven (or six) jobs where the tests pass, the type of the array says that the entries are `Int64`, as in the above output, whereas the entries are `Any` in the (first) failed job.
I would understand if the type would be `Array{Any,2}` since Julia 1.3, but I cannot reproduce this `Any` situation in Julia 1.3 or Julia 1.4.
And how can it happen that the test result depends on the used GAP?

**Comment by fingolfin** [comment]
These failures are flukes, caused by some Travis VMs still using Julia 1.3.0-rc5. Once all are upgraded to 1.3.0 this issue will resolve itself

**Comment by fingolfin** [comment]
This went away for #300 now, as predicted
