### ISSUE TITLE
More examples in README (at least) or documentation

### ISSUE THREAD

**Issue by kirtsar** [oscar-system/GAP.jl#303]
It is not clear what can be done right now. 

Actually, I can't even build a permutation , and there is no hints how I can do it:

```julia
x = GAP.julia_to_gap((1,2,3)(4,5))               # NO
x = GAP.Globals.Permutation([1,2,3])          # nope
x = GAP.Globals.Permutation((1,2,3)(4,5))  # no way
G = GAP.Globals.SymmetricGroup(3)
x = GAP.Globals.Random(G)                      # well ... sort of
```

**Comment by fingolfin** [comment]
Yes, documentation is TODO. In the meantime, looking at the tests gives some hints:
```
julia> @gap (1,2,3)
GAP: (1,2,3)
```
Or you can do:
```
julia> GAP.Globals.PermList(GAP.julia_to_gap([2,3,1]))
GAP: (1,2,3)
```

**Comment by fingolfin** [comment]
@ThomasBreuer can you look into this, and in particular work a bit on the documentation for GAP.jl? Looking at https://oscar-system.github.io/GAP.jl/dev/ we really need at least a basic intro as to what the package is about (could be based on README? Although it needs to be improved there, too). And an example. And anything else you can think of... (If it helps, I could also sit down later and try to write an issue with a list of specific ideas on what we could/should do, but I figure you will have plenty idea on what could be done here on your own ;-)

**Comment by ThomasBreuer** [comment]
Yes.
(Part of what is needed can be taken from the JuliaInterface manual.)

**Comment by fingolfin** [comment]
I believe the documentation is now adequate in this regard.
