### ISSUE TITLE
return missing rather than noting

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/GAP.jl#317]
for missing entries in lists

**Comment by kalmarek** [comment]
e.g.
```julia
function ElmList(x::GapObj,position)
    o = ccall( :GAP_ElmList,
               Ptr{Cvoid},
               (Any,Culong),
               x,Culong(position))
    return ifelse(o == nothing ? missing : o)
end
```
BUT this functions spills type unstability all over the code. It'd be much better to implement something along:
```julia
function guess_type(obj::GapObj)
    Globals.IsList(obj) && return eltype(obj)
    Globals.IsRecord(obj) && return Any
   T = (....) # something else, like a list of different typs for number types
   return T
end

ElmList(x::GapObj,position) = ElmList(guess_type(x), x, position)

function ElmList(::Type{T}, x::GapObj, position) where {T}
    o = ccall( :GAP_ElmList,
               Ptr{Cvoid},
               (Cvoid,Culong),
               x,Culong(position))
    return unsafe_read(convert(Ptr{T}, o))::T
end
```
so that unstability is contained inside `guess_type` (or can be avoided, when the type is known).

It seems, for the types that we are actually able to convert (from `gap_to_julia.jl`) a short, static list of types would be enough...

**Comment by fingolfin** [comment]
All sounds plausible on the surface. I don't have time to work on any of that. Perhaps @ThomasBreuer has? Otherwise, patches are of course also welcome (I mean that in a non-snarky way; I understand this is not your job and you may not have time for it).

**Comment by kalmarek** [comment]
I don't know where does the `nothing` come from when You call `ElmList`, so someone more knowledgeable needs to help me on this;

**Comment by ThomasBreuer** [comment]
Concerning the question whether `GAP.ElmList` should return `nothing` or `missing`,
I am in favor of `nothing`.
As far as I understand the use of `missing` in Julia, the idea is to make a lot of functions work without errors for arrays containing `missing` at some position; for example, one can sort such an array and compute its sum.
In GAP, it is not possible to sort or sum up a non-dense list such as `l:= [1,,3]`, and the attempt to access `l[2]` yields an error message; note that GAP does not have a `nothing` like object that could be returned.
Thus one could argue that `GAP.ElmList` for an unbound position should throw an error as well.
My argument for returning `nothing` instead would be that it is easier to check (afterwards) for `nothing` in Julia than to check (beforehand) with `GAP.Globals.ISB_LIST` whether the position in question is bound.

**Comment by ThomasBreuer** [comment]
@kalmarek `GAP.ElmList` calls the C function `GAP_ElmList`; in the case of an access to an unbound position, the return value is `0`; then `RAW_GAP_TO_JULIA` calls `julia_gap`, which finally returns `jl_nothing` for input `0`.

**Comment by kalmarek** [comment]
@ThomasBreuer, maybe I mis-interpret what is `ISB_LIST`, but the function of `missing` is precisely th gracefully indicate a missing value:
```julia
help?> missing
search: missing Missing MissingException ismissing nonmissingtype skipmissing

  missing

  The singleton instance of type Missing representing a missing value.

help?> Missing
search: Missing missing MissingException ismissing nonmissingtype skipmissing

  Missing

  A type with no fields whose singleton instance missing is used to represent missing
  values.
```

**Comment by ThomasBreuer** [comment]
@kalmarek, I would compare Julia's `missing` with GAP's `Unknown()` values (which are used rarely):
The idea behind is to let the user do computations with arrays, say, where some entries are not really needed, and the final result will contain certain `missing` values, but the non-`missing` values may be interesting.
This is not the way how unbound entries in GAP lists behave, as I sketched above.

**Comment by fingolfin** [comment]
Upon re-reading the Julia documentation, I agree with @ThomasBreuer 

Specifically, the [documentation for `nothing`](https://docs.julialang.org/en/v1/base/constants/#Core.nothing) says this (emphasis mine): 
> The singleton instance of type `Nothing`, **used** by convention when there is no value to return (as in a C void function) or **when a variable or field holds no value**.

While the [documentation for `missing`](https://docs.julialang.org/en/v1/manual/missing/) starts with the words:
> Julia provides support for representing missing values in the statistical sense [...]

And that's not at all what we want. And `1 + missing` is `missing`;  while `1 + nothing` gives an error, which is what I'd expect for a "hole in a list".

**Comment by fieker** [comment]
On Wed, Jan 22, 2020 at 03:17:02PM -0800, Max Horn wrote:
> Upon re-reading the Julia documentation, I agree with @ThomasBreuer 
> 
> Specifically, the [documentation for `nothing`](https://docs.julialang.org/en/v1/base/constants/#Core.nothing) says this (emphasis mine): 
> > The singleton instance of type `Nothing`, **used** by convention when there is no value to return (as in a C void function) or **when a variable or field holds no value**.
> 
> While the [documentation for `missing`](https://docs.julialang.org/en/v1/manual/missing/) starts with the words:
> > Julia provides support for representing missing values in the statistical sense [...]
> 
> And that's not at all what we want. And `1 + missing` is `missing`;  while `1 + nothing` gives an error, which is what I'd expect for a "hole in a list".
> 
In julia currently accessing an undefined entry throws an error.
a = Array(FlintZZ, 2)
2-element Array{fmpz,1}:
 #undef
 #undef

then a[1] is error
isassigned(a, 1) -> false
isdefined(a, 1) -> true
a[1] = 1
will change this to true and true

However,
a = [undef, undef]
makes a[1] work...
a = [undef, undef]
2-element Array{UndefInitializer,1}:
 array initializer with undefined values
 array initializer with undefined values

So, what do you want?

**Comment by kalmarek** [comment]
this will explain
```julia
help?> undef
search: undef UndefVarError UndefRefError UndefInitializer UndefKeywordError BoundsError RoundNearest RoundNearestTiesUp RoundNearestTiesAway RoundToZero @boundscheck QuoteNode

  undef

  Alias for UndefInitializer(), which constructs an instance of the singleton type UndefInitializer, used in array initialization to indicate the array-constructor-caller would like an
  uninitialized array.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> Array{Float64,1}(undef, 3)
  3-element Array{Float64,1}:
   2.2752528595e-314
   2.202942107e-314
   2.275252907e-314
```
just because something prints as `undef` desn't mean you can't access it
```
julia> w = [undef, undef];

julia> isdefined(w, 1)
false

julia> isassigned(w, 1)
true
```

**Comment by fieker** [comment]
On Wed, Jan 22, 2020 at 11:54:31PM -0800, kalmarek wrote:
> this will explain
> ```julia
> help?> undef
> search: undef UndefVarError UndefRefError UndefInitializer UndefKeywordError BoundsError RoundNearest RoundNearestTiesUp RoundNearestTiesAway RoundToZero @boundscheck QuoteNode
> 
>   undef
> 
>   Alias for UndefInitializer(), which constructs an instance of the singleton type UndefInitializer, used in array initialization to indicate the array-constructor-caller would like an
>   uninitialized array.
> 
>   Examples
>   ≡≡≡≡≡≡≡≡≡≡
> 
>   julia> Array{Float64,1}(undef, 3)
>   3-element Array{Float64,1}:
>    2.2752528595e-314
>    2.202942107e-314
>    2.275252907e-314
> ```
> just because something prints as `undef` desn't mean you can't access it
> ```
> julia> w = [undef, undef];
> 
> julia> isdefined(w, 1)
> false
> 
> julia> isassigned(w, 1)
> true

but w[1] will not throw an error...
julia> a = Array(FlintZZ, 2)
2-element Array{fmpz,1}:
 #undef
 #undef

julia> a[1]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(::Array{fmpz,1}, ::Int64) at ./array.jl:728
 [2] top-level scope at REPL[151]:1

julia> a = [undef, undef]
2-element Array{UndefInitializer,1}:
 array initializer with undefined values
 array initializer with undefined values

julia> a[1]
array initializer with undefined values

weird

**Comment by kalmarek** [comment]
`undef` is a shorhand for `UndefInitializer()`, you're creating array with two initializers (two objects), not an uninitialized array...
