### ISSUE TITLE
refactor gap_to_julia

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/GAP.jl#319]
mostly valid julia code but some pseudocode as well; comments welcome;
EDIT: draft is in https://github.com/oscar-system/GAP.jl/pull/323

**Comment by kalmarek** [comment]
* overloading julia constructors allow much more natural calls like `Matrix(obj)` than `gap_to_julia(Matrix, obj)`

I updated the code @fingolfin @ThomasBreuer; With hacks/backward compatibility at the end it passes the first ~ 60 tests in `test/conversion.jl`
I won't have much time this or next week to push it further, I'd be glad if anyone from `GAP.jl` take it over;

**Comment by ThomasBreuer** [comment]
@kalmarek @fingolfin I try to incorporate the ideas.

**Comment by kalmarek** [comment]
given what @fingolfin wrote https://github.com/oscar-system/GAP.jl/issues/315#issuecomment-577244963, I think this requires more consideration and overall time spent in design, as for now we have two intermingled layers of conversion;

In Polymake.jl we convert everything to julia understandable type whenever we can. the fast-track (without conversion) is hidden in low-level interface behind keyword, but I'd need to know more about gap↔julia interface...

**Comment by fingolfin** [comment]
@kalmarek could you perhaps turn this into a (non-working) PR? I.e. just copy&past your edits into/over `adapter.jl`, it's fine if it doesn't compile. But then this way, it's easy to inspect the diff, and also to comment on it line by line.

For GAP<->Julia, based on our experience designing several similar tools, Sebastian and me followed the design principle that at the lowest level, automatic conversions are kept to an absolute minimum. Higher level code can of course implement further conversions; but if these turn out to be "wrong" for some usecase, or inefficient, it's important to provide an escape hatch. Many interfaces between disparate systems unfortunately get this wrong and this then causes massive headaches down the road. I described this design philosophy in greater detail here: https://github.com/oscar-system/GAP.jl/wiki/Rules-for-conversion-between-GAP-and-Julia-objects

**Comment by kalmarek** [comment]
yes, I've read this document, but it documents more wishes than actual state (some containers are converted, some part of containers are wrapped, but those parts as standalone are converted?).
```julia
julia> GAP.julia_to_gap(Dict{Symbol, Any}(:aaa=>1, :bbb=>Int32(3)))
GAP: rec( aaa := 1, bbb := <Julia: 3> )

julia> x = GAP.julia_to_gap(Dict{Symbol, Any}(:aaa=>1, :bbb=>Int32(3)))
GAP: rec( aaa := 1, bbb := <Julia: 3> )

julia> GAP.julia_to_gap(Dict{Symbol, Any}(:aaa=>1, :bbb=>Int32(3), :ccc=>x))
GAP: rec( aaa := 1, bbb := <Julia: 3>, ccc := rec( aaa := 1, bbb := <Julia: 3> ) )

julia> GAP.julia_to_gap(Dict{Symbol, Any}(:aaa=>1, :bbb=>Int32(3), :ccc=>[x]))
GAP: rec( aaa := 1, bbb := <Julia: 3>, 
  ccc := <Julia: Main.ForeignGAP.MPtr[GAP: rec( aaa := 1, bbb := <Julia: 3> )]> )

julia> GAP.julia_to_gap(Dict{Symbol, Any}(:aaa=>1, :bbb=>Int32(3), :ccc=>[x, 1]))
GAP: rec( aaa := 1, bbb := <Julia: 3>, 
  ccc := <Julia: Any[GAP: rec( aaa := 1, bbb := <Julia: 3> ), 1]> )
```
when and what is converted seems to be a total random thing. `MPtr` really needs to be wrapped? I thought it's a native GAP object...

Anyway talking about inefficiencies with respect to converting, when we're looking at 100% interpreted code misses the point completely ;-) Case in point:
```julia
julia> let n = 1000000
           vec = collect(1:n)
           @time s = test_sum(vec)
           
           gap_list = @gap [1..1000000]
           @time gap_s = test_sum(gap_list)
           @assert s == gap_s
       end
  0.003597 seconds (5 allocations: 176 bytes)
  2.015631 seconds (18.00 M allocations: 350.890 MiB, 4.14% gc time)

julia> using BenchmarkTools

julia> gap_list = @gap [1..100]
GAP: [ 1 .. 100 ]

julia> @btime $gap_list[5]
  1.524 μs (8 allocations: 192 bytes)
5
```
we need 8 allocation for simple access and further 10 to add to an `Int`.

**Comment by kalmarek** [comment]
just one more note: in Polymake we have
https://github.com/oscar-system/Polymake.jl/blob/master/src/meta.jl#L262
which hides conversion behind a kwarg `keep_PropertyValue=false` (yes, we do convert everything by default; nobody complained about the performance, since it's not an issue)
