### ISSUE TITLE
printing of self-referring list crashes

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/GAP.jl#324]
```julia
julia> s = GAP.julia_to_gap( "[ 1, ~, 3 ]" )
GAP: "[ 1, ~, 3 ]"

julia> GAP.Globals.EvalString(s)
Error, Panic: tried to print a path of unsupported type 'component object'
Error showing value of type Main.ForeignGAP.MPtr:
ERROR: Error thrown by GAP
(...)
```

**Comment by fingolfin** [comment]
Huh, that's really odd. This works fine when called from GAP:
```
gap> [ 1, ~, 3 ];
[ 1, ~, 3 ]
gap> EvalString("[1, ~, 3]");
[ 1, ~, 3 ]
```
I can only speculates that `STATE(Tilde)` in GAP somehow ends up containing nonsense, but right now I have no clue what's going on here.

BTW, you can do these things more concisely using `@gap`: I.e., `@gap EvalString("[1, ~, 3]")` or even `@gap [1, ~, 3]`

**Comment by ThomasBreuer** [comment]
When GAP views the list, it uses `ViewObj`.
Julia's `show` method cannot use that, it calls GAP's `StringView`, which belongs to the GAPDoc package. (I had already told Frank about the current problem.)
Note that the idea behind `StringView` is to create a string that corresponds to what `ViewObj` prints, and is thus more suitable than `ViewString`.
And note that `ViewString` uses a GAP library method for the above list, hence it fails on self-referential objects, too; but this is a different problem.

**Comment by fingolfin** [comment]
To fix this, we should simply not use `StringView`. I can add a C function to JuliaInterface which invokes `ViewObj` but with output printed into a string. On the long run, we may want to integrate this into GAP proper, but for now this is the easiest way to handle it, I think.
