### ISSUE TITLE
JuliaExperimental fails on oscar-ci

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#350]
`JuliaExperimental` is failing on oscar-ci:

https://oscarci.mathematik.uni-kl.de/job/oscar/7393/artifact/logs/build-7393/JuliaExperimental.log

with errors like

```
# Input is:
vec:= GAPToNemo( c, [ 1, 2 ] );
# Expected output:
<<Julia: [1 2]>>
# But found:
<vector object of length 2 over Integers>
```

**Comment by fingolfin** [comment]
My guess is that this this is caused by the recent MatrixObj changes in the GAP master branch. Only that we really shouldn't be using the GAP master branch here anyway... I assume this is an issue with the OSCAR CI setup. I will investigate.

CC @ThomasBreuer

**Comment by mohamed-barakat** [comment]
@fingolfin Thank you very much.
