### ISSUE TITLE
Document the release process of this package

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#352]
We should document the release process of this package. Here is how I *think* it works (based on my bad memory); I'll update this during the next release and then we can add it to a file in the repository, e.g. `etc/README.md`  or `README.maintainer`.

1. Switch to the `master` branch and `cd` into the root directory of the git repository.

2. Update the version of the Julia and GAP packages by invoking the script `etc/update_version.sh`  with the new version as argument. Example: `etc/update_version.sh 0.3.0` (by the way, this is shell script which calls `perl` right now; it would make sense to rewrite it as a Julia script to avoid the need for perl).

2. `git push`

3.  Ideally wait for Travis CI to complete the full CI tests for the commit you just pushed

4. Comment on the commit on GitHub with the message `@JuliaRegistrator register` ([see here for an example](https://github.com/oscar-system/GAP.jl/commit/159c6fd580e9d9cfbc1877a0856c4a5f9ecaba4d)).

The latter works because we have set up a GitHub Action for [Julia TagBot](https://github.com/marketplace/actions/julia-tagbot) to tag and make the release automatically.

**Comment by fingolfin** [comment]
Ooops, didn't mean to actually trigger the JuliaRegistration bot...

**Comment by mohamed-barakat** [comment]
This is funny :)
