### ISSUE TITLE
GAP.jl 0.3.3

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#366]
I understand the necessity of compiling a minimal amount of packages when installing `GAP.jl`. With a fresh `GAP.jl` v0.3.3 `HomalgProject.jl` fails to load as the package `IO` was not compiled. This means that

`pkg> add HomalgProject`

is not enough anymore.

Is there a possibility to require a package to `fully build`?

**Comment by fingolfin** [comment]
No. The idea is to use the GAP package PackageManger to compile packages, and also soon to install them: the idea is to drop all packages except the essential ones and PackageManager, and provide a Julia command like `GAP.install_package` instead.

**Comment by mohamed-barakat** [comment]
Is it possible to compile `io` for the moment for `HomalgProject` to load, function, and pass the tests until you provide `GAP.install_package` which I can explicitly call to "build" `HomalgProject`?

**Comment by mohamed-barakat** [comment]
Today I switched `HomalgProject.jl` to access Singular's interpreter via `Singular.jl` using [`OscarForHomalg`](https://github.com/homalg-project/OscarForHomalg) bypassing `IO_ForHomalg`. But `ToolsForHomalg` (which is distributed with GAP 4.11.0) has an explicit dependency of `IO`, so I am currently stuck.

**Comment by fingolfin** [comment]
Unfortunately I am busy with other things right now, plus being somewhat ill since this afternoon, so getting this done might take me a few more days.

But in the meantime, if you want to urgently continue, you could simply invoke the relevant PackageManager commands to install `io` yourself. This is ultimately what `GAP.install_package` will do anyway.

**Comment by fingolfin** [comment]
I just released GAP.jl 0.3.5 which allows doing `GAP.Packages.install("io")`.
