### ISSUE TITLE
Documenter.jl refuses to display julia_to_gap, gap_to_julia

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#370]
I set up some basic Documenter.jl framework which displays at least some of our Julia docstrings on https://oscar-system.github.io/GAP.jl/dev/ -- much more work is needed, but it is a start.

However, no matter what I tried, I couldn't get it to display the docstrings for `julia_to_gap` and `gap_to_julia`. And contrary to what the Documenter.jl manual says (or at least to how I understand it), not even warnings are shown about these docstrings not appearing in the manual.

Yet when I use the `@autodocs` command, they do appear! Now I could just go for that (and perhaps we should, for simple convenience), but it annoys me that we kind of have to...

@ThomasBreuer thoughts?

**Comment by ThomasBreuer** [comment]
@fingolfin The functions appear as soon as `docs/src/index.md` contains 
````
```@meta
CurrentModule = GAP
```
````
Note that the two functions are not exported, whereas `FFE`, `GapObj`, and the macros (for which `Documenter.jl` found the docstrings) are exported.

**Comment by ThomasBreuer** [comment]
@fingolfin Pull request #372 should solve the problem.

(One more remark:
In the old setup, I got warnings about the missing docstrings when running `julia make.jl` in the `docs` directory.)
