### ISSUE TITLE
Installing GAP.jl simultaneously within multiple Julia versions may crash

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#377]
Based on empiric evidence, it seems that using a GAP compiled against Julia 1.2 from within Julia 1.3, or vice versa, does not work as it results in a crash. I suspect that this is due to subtle differences in the Julia kernel that affect our Julia GC integration (things like: "the content of some internal struct changed around, so our code doing this gets broken).

The ideal solution would be to find that code in the GAP kernel as well as Julia interface and remove it. Alas, that may not be feasible (we may not be able to identify the code, and/or there might be no way to avoid it). Perhaps @rbehrends has some thoughts on it.

The alternative then is to make sure we don't used code compiled for one Julia version in another. But right now, if one installs a specific version of GAP.jl , say 0.3.4, then that gets a install in a subdirectory like `~/.julia/packages/GAP/6rBgt`, and in there we install a copy of GAP. That copy then is used whenever GAP.jl 0.3.4 is loaded, regardless of whether it is Julia 1.2, 1.3, 1.4, or whatever. As a result if GAP.jl was installed with Julia 1.2, and we then try to load it in 1.3, we get a crash, and vice versa (have not yet tried what happens with 1.4).

One way to resolve this would be to use the fact that GAP supports out-of-tree build: instead of compiling GAP directly in `~/.julia/packages/GAP/6rBgt/gap-4.11.0`, we could instead create a subdirectory `~/.julia/packages/GAP/6rBgt/gap-4.11.0-julia-1.2` and run `../gap-4.11.0/configure && make` in there. Then use that dir as GAP root. This way, we share the source code but get separate binaries.

However, this does not resolve the issue for the C kernel of JuliaInterface. Perhaps there actually is no issue there, then we are done. Otherwise, we'll need a way to also compile and load different versions of that kernel extension...

There is a dual aspect to all this: right now, if one installs GAP 0.3.3 and 0.3.4 in parallel, they each get their own full copy of GAP. In particular, upgrading GAP.jl does not reuse the existing GAP installation. That's a bit annoying...

We could overcome this by installing GAP into a different place, e.g. into `~/.julia/packages/GAP/gap-4.11.0`. I don't see a downside to this right now (other than that Julia resp. Pkg.jl might not like us do that?). In that case, we could still have the dir in which we compile GAP in the same place relative to GAP.jl, i.e., in `~/.julia/packages/GAP/6rBgt/gap-4.11.0-julia-1.2`. Or, assuming we are reasonably sure we'll not use funky custom compilation options in future GAP.jl versions, we could use build dirs like `~/.julia/packages/GAP/gap-4.11.0/v1.2` or so.

BTW, compiled packages other than JuliaInterface should be fine to use across different Julia versions.

**Comment by fingolfin** [comment]
To clarify: actually, right now we install GAP relative to the GAP.jl package directory, which might be elsewhere than `~/.julia`, if the user uses a custom environment. Thus my suggestions further fork here: we could have one copy of GAP per environment. Or really just a single global one.

Having a single global one requires the least resources, and grants fast installation of GAP in custom environments. However, it means that if that single copy of GAP somehow gets messed up, everything breaks. Not sure what people prefer. I think I'd prefer a single global copy, but I don't claim to have thought through all consequences.

**Comment by mohamed-barakat** [comment]
Since the current GAP, thanks to your efforts, supports an out-of-tree-build I am strongly in favor of the option you propose. We just need to check if Julia's `Pkg` will start to complain about unidentifiable subfolders in `~/.julia/packages/GAP/`, but I doubt it.

**Comment by rbehrends** [comment]
> The ideal solution would be to find that code in the GAP kernel as well as Julia interface and remove it. Alas, that may not be feasible (we may not be able to identify the code, and/or there might be no way to avoid it).

This is puzzling, because I can't easily see where we'd have such code. We mostly go through the API, which should be version-agnostic, but even struct layout changes in Julia are generally only done by appending fields to an existing struct in order to preserve backwards compatibility (according to at least some of the Julia devs), which should not hurt us.

One possible candidate for incompatibilities that I can think of is the task switching mechanism, which has seen some changes between versions.
