### ISSUE TITLE
WARNING: could not import Base.hasproperty into GAP

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#382]
There seems to be an issue with `hasproperty`:

https://oscarci.mathematik.uni-kl.de/job/oscar/8184/execution/node/140/log/

**Comment by ThomasBreuer** [comment]
The warning looks as if a Julia version <= 1.1 was used in the tests:
`Base.hasproperty` is defined only from Julia 1.2 on,
and I can reproduce the warning with Julia 1.1 but not with Julia 1.2 or 1.3, by calling `import Base: hasproperty`.

**Comment by fingolfin** [comment]
Jenkins needs to be switched to Julia 1.3. I already notified @rbehrends about this and another issue yesterday, I hope it will be resolved son

**Comment by rbehrends** [comment]
Jenkins has been on 1.3 since last night. Polymake.jl and Oscar.jl tests fail currently because of a dependency issue, HomalgProject.jl has issues with a missing LinearAlgebra Julia package.

**Comment by mohamed-barakat** [comment]
`LinearAlgebra` (`uuid="37e2e46d-f89d-539d-b4ee-838fcccc9c8e"`) is needed by `JuliaExperimental` but it is not a dependancy in `GAP.jl` v0.3.4. Wouldn't it make more sense to add it to `GAP.jl`?

**Comment by mohamed-barakat** [comment]
@rbehrends: I am puzzled by the context which produces this error on jenkins:

https://oscarci.mathematik.uni-kl.de/job/oscar/8219/artifact/logs/build-8219/HomalgProject.jl.log

Everything is running here:

https://travis-ci.com/github/mohamed-barakat/HomalgProject.jl/jobs/297893533

**Comment by fingolfin** [comment]
@mohamed-barakat Hmm, `JuliaExperimental` only uses `LinearAlgebra` if it is available, so it isn't a list dependency on purpose.

**Comment by fingolfin** [comment]
Ah wait, I see: `zlattice.jl` uses `LinearAlgebra`, and it is unconditionally included by `zlattice.g` which in turn is always loaded by `init.g`. So @ThomasBreuer and me need to fix that.

**Comment by fingolfin** [comment]
The issue reported here originally is resolved, and I extracted the LinearAlgebra related one into an issue of its own.

**Comment by mohamed-barakat** [comment]
Thanks Max
