### ISSUE TITLE
access to Julia variables from GAP

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#390]
Currently Julia module objects in GAP admit access to variables of the module via `\.`.
```
gap> Julia;
<Julia module Main>
gap> Julia.GAP;
<Julia module GAP>
gap> Julia.sqrt;
function( arg... ) ... end
gap> JuliaEvalString( "a = 1" );
1
gap> Julia.a;
1
```
One can access Julia variables also with `JuliaGetGlobalVariable`, but there are differences.
First, there is a problem with caching.
```
gap> JuliaEvalString( "a = 2" );
2
gap> Julia.a;
1
gap> JuliaGetGlobalVariable( "a" );
2
```
Second, functions and modules get wrapped with `_JuliaFunction` and `_WrapJuliaModule` by the access with `\.` (see above) but not by `JuliaGetGlobalVariable`.
```
gap> JuliaGetGlobalVariable( "sqrt" );
<Julia: sqrt>
gap> JuliaGetGlobalVariable( "GAP" );
<Julia: Main.GAP>
```
(Third, see #175 .)

The caching problem must be solved, the easiest solution is to remove the caching.
Concerning the other differences, what do we want?
Which of `<Julia: sqrt>` and `Julia.sqrt` is better?

**Comment by fingolfin** [comment]
Yeah, let's remove the caching.

As to the handling of functions: `Julia.sqrt` is nicer in the sense that it can be used as a function more efficiently. The result of `JuliaGetGlobalVariable( "sqrt" )` is nicer in that it prints nicer. So here my solution would be to add nicer `(Print|View|Display)(String)?` methods; to do that, easiest would be to export `IS_JULIA_FUNC` from the kernel to GAP, and then install high-ranked methods for `IsFunction` which check `IS_JULIA_FUNC` and then either print `<Julia: FOOBAR>`, or else call `TryNextMethod` .

Finally, once these improvements are in place, I am not sure whether we even want to keep `JuliaGetGlobalVariable`? The only reason I can think of (beyond backwards compatibility, of course!) is performance: is perhaps `JuliaGetGlobalVariable("a")` considerably faster than `Julia.a`, if called "often enough"?

**Comment by ThomasBreuer** [comment]
Pull request #423 deals with the (hopefully) non-controversial parts of this issue:

- Caching the values of arbitrary Julia variables in GAP's `IsJuliaModule` objects cannot work because the values may be changed in Julia.
  Caching Julia modules is safe because they can be imported only once into Julia.
  Thus the `storage` components in the `IsJuliaModule` objects should be restricted to Julia modules.

- The current `Unbind\.` method for `IsJuliaModule` means to remove the variable in question from the `storage`, and a subsequent `IsBound\.` or `\.` call checks whether the Julia variable exists or fetches this variable, respectively; I think this makes no sense,
  `Unbind\.` should call `Error`, in the same way as `\.\:\=` does already.
  (The `IsBound\.` method is correct.)

- Concerning the performance of `JuliaGetGlobalVariable( "a" )` vs. that of
`Julia.a`, for a function `a`:
  `x:= Julia.sqrt;` yields a GAP wrapped function (not in `IsJuliaObject`),
  `y:= JuliaGetGlobalVariable( "sqrt" );` yields an object in `IsJuliaObject`.

  The *assignment* to `x` is slower than that to `y`, but *calling* the function `x` is much faster than calling `y`.
  Each access `Julia.sqrt` creates the wrapped function anew (as soon as the caching gets removed), but still `Julia.sqrt( 5 );` or `Julia.Base.sqrt( 5 );` is cheaper than `y:= JuliaGetGlobalVariable( "sqrt" ); y( 5 );`.
  I see no disadvantage of the GAP wrapped function, compared with the `IsJuliaObject` variant.
  (When one passes the wrapped function to Julia then it gets automatically converted/unpacked: `GAPToJulia( x )` yields the object `y`.)
  Here is an example of timings.

```
gap> for i in [ 1 .. 100000 ] do
>    od; time;
6
gap> for i in [ 1 .. 100000 ] do x:= Julia.Base.sqrt;
>    od; time;
163
gap> for i in [ 1 .. 100000 ] do x( 5 );
>    od; time;
33
gap> for i in [ 1 .. 100000 ] do x:= Julia.Base.sqrt;  x( 5 );
>    od; time;
203
gap> for i in [ 1 .. 100000 ] do y:= JuliaGetGlobalVariable( "sqrt" );
>    od; time;
64
gap> for i in [ 1 .. 100000 ] do y( 5 );
>    od; time;
501
gap> for i in [ 1 .. 100000 ] do y:= JuliaGetGlobalVariable( "sqrt" );  y( 5 );
>    od; time;
769
```

After the change of the caching in `IsJuliaModule` objects, more questions arise:

- What is the function `JuliaSymbolsInModule` good for?
  It returns the list of names (strings) of the currently stored variables.
  This was never guaranteed to cover all variables of the Julia module, and will be completely useless after removing the storage for variables accessed with `\.`
  A safe variant of a function with this name would always return a new list,
  which is created by running through the currently available variables on the Julia side.

- The function `ImportJuliaModuleIntoGAP` triggers an import of the Julia module into Julia and creates its `IsJuliaModule` object on the GAP side.
  Up to now, it also triggers that storage components for the currently available variables of the module are created; after the removal of the general storage, this is reduced to submodules (non-recursively).
  What is expected from this function?

**Comment by fingolfin** [comment]
`JuliaSymbolsInModule` can IMHO go, see my PR for that.

For `ImportJuliaModuleIntoGAP` I think the idea was that this is meant to be roughly analog to `import` in Julia.

**Comment by fingolfin** [comment]
@ThomasBreuer I am not sure what the status of this, do I or we still need to do something?

**Comment by ThomasBreuer** [comment]
@fingolfin I will adjust the documentation accordingly; besides that, the problems are solved.
