### ISSUE TITLE
Acknowledge DFG funding in the package README & manual

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#405]
Other projects within the SFB such as Polymake.jl, Singular.jl, Nemo.jl etc. should of course also do this, if they don't already (ping @fieker -- agreed?)

**Comment by fieker** [comment]
On Tue, Apr 07, 2020 at 04:37:57PM -0700, Max Horn wrote:
> Other projects within the SFB such as Polymake.jl, Singular.jl, Nemo.jl etc. should of course also do this, if they don't already (ping @fieker -- agreed?)
> 
Yes, good idea
