### ISSUE TITLE
problem with `import` statements in files loaded via `JuliaIncludeFile`

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#419]
Currently I run into the following problem.
I start GAP, load its JuliaInterface package, and then call `JuliaIncludeFile` for a file containing a Julia module.
If this Julia module tries to import GAP (which makes sense if the Julia code wants to call GAP functions) and also some other Julia module then strange things happen.

**Case 1**:
The included file is `testGP.jl` and looks as follows.
```
module testGP
import GAP; println( "after import GAP" )
import Primes; println( "after import Primes" )
end
```
The GAP session looks as follows.
```
gap> LoadPackage( "juliai", false );;
gap> Julia.Base.sqrt(5);                 # the interface works
<Julia: 2.23606797749979>
gap> JuliaIncludeFile( "testGP.jl" );    # including seems to work
after import GAP
after import Primes
gap> Julia.Base.sqrt(5);                 # but now the interface is broken
Error, MethodError: Cannot `convert` an object of type Main.ForeignGAP.MPtr to an obj\
ect of type Main.GAP.GapObj
[...]
```

**Case 2**:
The included file is `testPG.jl` and looks as follows.
```
module testPG
import Primes; println( "after import Primes" )
import GAP; println( "after import GAP" )
end
```
The GAP session looks as follows.
```
gap> LoadPackage( "juliai", false );;
gap> Julia.Base.sqrt(5);                # the interface works
<Julia: 2.23606797749979>
gap> JuliaIncludeFile( "testPG.jl" );   # including runs into an error
after import Primes
Error, LoadError: InitError: MethodError: Cannot `convert` an object of type Main.For\
eignGAP.MPtr to an object of type Main.GAP.GapObj
[...]
```
If the Julia module imports just GAP or does not import GAP then the problem does not occur.
The effect is not changed when I replace `Primes` by `Nemo`.

(I am using Julia 1.4.0 with the GAP 4.11.0 which was installed by Julia using the current standard procedure, together with the master branch of GAP.jl, whose JuliaInterface was compiled relative to Julia's GAP 4.11.0.
GAP must be started with `-E`, otherwise command line editing does not work; as far as I understand, this is the problem described in issue #415.)

**Comment by ThomasBreuer** [comment]
Update:
With `Pkg.update( "GAP" )` and `Pkg.build( "GAP" )`, I got a new artifact containing GAP 4.11.0,
and with this setup, the behaviour in both of the two above cases is that described for Case 1.

(The line editing problem for GAP has vanished in the new setup.
There is still the problem that the `Browse` package can be compiled but GAP cannot load it and claims that the .so file is not found.)

**Comment by fingolfin** [comment]
Re line editing: I am working on that but the term has started and I have a babysitter only for a few hours on 3 days the week, so progress is slow. But I have a solution, stay tuned.

I'll look into this, too.


(BTW, unrelated and not solving the line editing issue, but: I just discovered that from the Julia prompt you can trivially get to a GAP prompt by entering `GAP.Globals.SESSION()`; when you are done, exit it, and you are back to the Julia prompt. Seems to work great so far!)

**Comment by ThomasBreuer** [comment]
Just for the record:
With a GAP session started from Julia via `GAP.Globals.SESSION()`, the inputs described above work without problem. In this situation, just the line editing seems to be missing.

(At first glance, I had thought that the `GAP.Globals.SESSION()` approach in Julia could also solve my old problem that a Jupyter notebook with GAP kernel crashes as soon as GAP loads JuliaInterface.
But of course the Julia kernel does not give access to the GAP session.)

**Comment by fingolfin** [comment]
OK, interesting. I still need to get to the bottom of this.

Regarding Jupyter integration: Well, I was also wondering if we could use this... indeed it's not quite *that* simple. But perhaps we could somehow write our own `IGap.jl` based on `IJulia`, but instead of evaluating inputs in Julia, we evaluate them in GAP etc. -- "how hard can it be???" ;-)

**Comment by ThomasBreuer** [comment]
@fingolfin I cannot reproduce these problems anymore with the current GAP.jl. Shall we close the issue?
