### ISSUE TITLE
Add constructors for conversion from GAP to Julia

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#428]
We should salvage at least part of PR #323 by @kalmarek ! That is, I very much would like to have constructors for BigInt, BigFloat, Float64, Int64, etc. etc. that accept a `GapObj`, and which would throw a `GAP.ConversionError` in case of a failure. I'd also refactor `gap_to_julia` to use these constructor where appropriate / sensible (just as PR #323 did).

At least for the basic types, this should be easy enough. For containers, all kinds of pitfalls lurk, as also discussed in issue #319, but that shouldn't stop us from at least providing the basic ones. I.e. this is not an "all-or-nothing" situation, we can do it gradually.

@ThomasBreuer can you look into this?

**Comment by ThomasBreuer** [comment]
@fingolfin Yes

**Comment by fingolfin** [comment]
This is what I meant when I wrote:
> At least for the basic types, this should be easy enough. For containers, all kinds of pitfalls lurk [...]

I.e., for starters I'd already be happy if we had at least constructors for Int, BigInt, Float, BigFloat, String, ... even if we had none for containers (at least at first)

BTW, I would not use a second argument for constructor to pass the recursion dictionary; I'd rather use a keyword argument, just as we do with `gap_to_julia` methods.

Anyway, In the end, I don't care so much whether constructors are implemented using `gap_to_julia`, or the way around, or a mixture, as long as it works and is understandable :-). If you think writing the constructors using `gap_to_julia` is preferable, that's good enough for me.

BTW, one could *also* think about providing `convert` methods -- see also <https://discourse.julialang.org/t/4159/24> and <https://discourse.julialang.org/t/4159/35>

**Comment by ThomasBreuer** [comment]
@fingolfin Can this issue be closed?
