### ISSUE TITLE
detect whether JuliaInterface (and GAP.jl) fit to a running GAP 

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#433]
With the current master GAP.jl, the following happens:
I start a GAP that does *not* fit to the master GAP.jl, for example a master GAP,
and erroneously call`LoadPackage( "JuliaInterface" )` at the GAP prompt.
If GAP finds the JuliaInterface of the master GAP.jl then the following message appears.
```
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Building GAP → `/.../pkg/GAP.jl/deps/build.log`
```
Apparently GAP.jl has noticed (at the beginning of `src/GAP.jl`) that the GAP in question does not fit to it, and now it tries to build GAP.
This cannot help in the current situation because GAP is already running, thus I think an error message would be appropriate.
Like in the later code in `src/GAP.jl`, one could check whether `cglobal("GAP_Initialize")` runs into an error, and signal an error if the global variable exists.

Ideally, one would wish that the `AvailabilityTest` function of JuliaInterface checks whether the current GAP and the intended GAP.jl fit together.
This function knows the GAP root paths and the Julia version, but can it safely assume that it finds the interesting files in `../../deps`? (This seems to work even with symbolic links to package directories.)
If yes then the `AvailabilityTest` function of JuliaInterface could check whether the relevant `deps-...` file is available and contains a valid root path of the running GAP, and could signal nonavailability if not.

I can provide a pull request if this sounds sensible.

**Comment by fingolfin** [comment]
> Apparently GAP.jl has noticed [...] that the GAP in question does not fit to it

Not quite (or perhaps I misunderstand): At the moment, GAP.jl *always* assumes that it is used with a GAP that was built as part of GAP.jl. Period. 

The only way to use a custom GAP with it is via an artifacts override, and even that is incomplete.

So there are multiple issues to consider here:

1. Do we want to allow using GAP.jl / JuliaInterface with an "alternative" GAP provided by the user? Might be handy for us, for testing against the GAP master branch (but that is a special case which could perhaps be achieved by other means with less work).
2. Should/could JuliaInterface be able to inform GAP.jl about the "active" GAPROOT, and could GAP.jl then use that?
3. Despite all efforts, we can still have mismatches: the following must match:
   - the GAP version used to compile JuliaInterface
   - the Julia version used to compile GAP and used to run it / run GAP.jl
   - the GAP.jl version
   - the version of JuliaInterface (must match the GAP.jl version, and that of its kernel extension)
   - the JuliaInterface kernel extension (must be compiled against the right GAP & Julia)
   But we only check a fraction of these -- perhaps we ought to check more?

You ask whether JuliaInterface can "safely assume that it finds the interesting files in `../../deps` -- I don't understand which "interesting files" you refer to? 

What seems to be the main concern to me is that JuliaInterface can only ask Julia to load the module `GAP`, but that may not actually be the case (if the user never did `Pkg.add("GAP")`, and even if it works, it might be a different version of GAP.jl than the one we need. This could in principle all be solved, but the question is: is it worth it? (see also issue 1 above)

For now, it is most important (in terms of what we promised to the DFG) that GAP.jl can be used from the Julia side without a hitch. Using it from GAP also is important, but we never (AFAIK) promised that you can use it from an arbitrary self-compiled GAP. While I would not object to doing that, I think it's not a high priority, and there are more important things to solve. 

Adding more sanity checks and warnings or errors if we for whatever reason end up with mismatch components would be very good, though.

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks.
My point is just what you write in the end:
Users will have various versions of more or less outdated packages, and it is likely that one uses by chance some combination that is not the expected consistent current version of everything.
Thus it is helpful to get warnings or error messages in such cases.
For example, several GAP versions were installed due to the recent changes in the build system of GAP.jl, and one has to be careful to call the latest one.

In particular, the point for me is not that I want to support various versions of GAP by one GAP.jl.
For example, I have given up the idea to use GAP.jl with the GAP master branch version since the latter has removed some kernel functions that are used in GAP.jl, see #410.

Concerning the question about "the interesting files":
From the viewpoint of JuliaInterface which has to decide whether it can be loaded, the question is whether the relative path `../../deps/deps-....jl` (for the Julia version in question) can be assumed to work; if yes then the GAP root path listed in this file can be compared with the root paths of the GAP which is running.

**Comment by fingolfin** [comment]
I just made PR #436 which should resolve the issue in #410 (I've not yet have time to try GAP master with GAP.jl myself, but let me know if there are more issues).

Thank you for the explanation of why accessing `../../deps/deps-....jl` is useful, I see now. I think that yes, it is safe to access those: if we ever decide to change or move them, then we'll simply have to adjust this in build.jl and JuliaInterface in tandem. Not that I have plans to change this...
