### ISSUE TITLE
How to get sublists of a GAP list?

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#438]
```
julia> L = GAP.julia_to_gap(1:100)
GAP: [ 1 .. 100 ]
```
Is there an easy way to get the sublist `L{[ a .. b ]}` as a GAP list?

**Comment by mohamed-barakat** [comment]
Thank you very much. It works for me locally. I would be happy to see this supported by `GAP.jl`.

**Comment by fingolfin** [comment]
The 2nd and 3rd method seem plausible to me, but the first one, `Base.getindex(x::GapObj, l::GapObj) = GAP.Globals.ELMS_LIST(x, l)`, seems problematic: what if `l` is e.g. a big GAP integer, or a string? We do allow `dict["key"]` in GAP theses days. Then we should not call ELMS_LIST but ELM_LIST....  Of course we could check the TNUM or something in there; but it might be safer to just omit this method (or perhaps have it in, but commented out, with a comment explaining it). I would hope that the other two methods should be enough to cover @mohamed-barakat's needs?

**Comment by mohamed-barakat** [comment]
PR #444 does all that I need.

**Comment by ThomasBreuer** [comment]
done because of #444
