### ISSUE TITLE
installation problem for version 0.3.5

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#447]
The following is likely irrelevant after the next release of GAP.jl, due to the completely changed build system.
However, when I install Oscar 0.3.0 from scratch, I run into the following problem.
(Oscar 0.2.0 does not have GAP.jl in its dependencies, thus I need 0.3.0.)
I remove all Oscar.jl related packages from my `.julia/packages`, download Oscar 0.3.0, start Julia 1.3.0 and enter `using Pkg; Pkg.develop( PackageSpec( path = ".../Oscar.jl-0.3.0" ) )`.
Then I enter `using Oscar` and get an error message concerning GAP.jl.
```
ERROR: LoadError: InitError: ccall: could not find function julia_gap
Stacktrace:
 [1] RAW_GAP_TO_JULIA(::Ptr{Nothing}) at /.../.julia/packages/GAP/4od8v/src/ccalls.jl:6
```

The problem occurs independent of Oscar, when I just install GAP.jl 0.3.5 from scratch:
I remove all GAP.jl related packages from my `.julia/packages`, start Julia 1.3.0 and enter
`using Pkg; Pkg.add( "GAP" )`.
Then Julia says ``Building GAP → `~/.julia/packages/GAP/4od8v/deps/build.log``, eventually
the Julia prompt appears, but then entering `using GAP` yields essentially the error message mentioned above.

**Comment by fingolfin** [comment]
Can you also reproduce this with Julia 1.3.1 or 1.4.1?

**Comment by fingolfin** [comment]
In addition, is this on Linux? Which distro? I cannot (yet) reproduce this, I am afraid.

**Comment by ThomasBreuer** [comment]
@fingolfin 
Julia 1.3.1 and Julia 1.4.0 show the same behaviour.
According to `lsb_release -a`, the operating system is `Ubuntu 18.04.4 LTS`.

**Comment by ThomasBreuer** [comment]
I cannot reproduce this problem with the current GAP.jl (and Julia 1.4).
