### ISSUE TITLE
Add automated CI tests for the GAP.prompt()

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#460]
Right now I am not aware of a "good" way to test GAP.prompt(); but I'd really like to have one, so that when an issue like #458 pops up, then the fix (here in #459) can also include a test that verifies the issue is gone.

One way to go about this might be to use [pexpect](https://pexpect.readthedocs.io/en/stable/index.html) which can be used to automate interactive command line utilities. (Of course if somebody knows a pure-Julia way to do the same, I'd also be happy to use that). This can also be handy for other kinds of tests, as it allows to emulate what an actual user would experience very closely.

I think we need to do roughly this:
1. add `pip install pexpect` into `.travis.yml`
2. add a script to `etc` which performs the required test using `pexpect`
3. call that script from `.travis.yml`

**Comment by fingolfin** [comment]
Perhaps testing the Help system might also benefit from such a thing? @ThomasBreuer ?

**Comment by fingolfin** [comment]
Sp perhaps we should just use the [Python package pexpect](https://pexpect.readthedocs.io), it's not like it is hard; a simple attempt:
```
>>> import pexpect
>>> child = pexpect.spawn('julia-1.5 --project=proj-1.5')
>>> child.expect('julia> ')
0
>>> child.sendline('using GAP')
10
>>> child.expect('julia> ')
0
>>> child.sendline('GAP.prompt()')
13
>>> child.expect('gap> ')
0
>>> child.sendline('1+1;')
5
>>> child.expect('gap> ')
0
>>> child.sendline('1:1;')
5
>>> child.expect('gap> ')
0
>>> child.sendline('Error("foo");')
14
>>> child.expect('brk> ')
0
>>> child.sendline('quit;')
6
>>> child.sendline('quit;')
6
>>> child.expect('julia> ')
0
```

**Comment by ThomasBreuer** [comment]
Not only the help system, there are also other interactive features like Julia's REPL menus which can be tested then.

**Comment by fingolfin** [comment]
Just learned about https://gitlab.com/wavexx/Expect.jl which we can use for this, too
