### ISSUE TITLE
building GAP.jl fails in a docker container running ubuntu:latest

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#462]
In the attempt to debug a failure on travis I am trying to build `GAP.jl` in a docker container running ubuntu (ubuntu:latest). The build fails. The log file is attached.

[build.log](https://github.com/oscar-system/GAP.jl/files/4646432/build.log)

**Comment by fingolfin** [comment]
```
cc1: warning: /usr/include/julia: No such file or directory [-Wmissing-include-dirs]
/root/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0/src/gap.c:54:10: fatal error: julia.h: No such file or directory
```

This looks like that contain has a broken Julia installation

**Comment by fingolfin** [comment]
How was `julia` installed in this container?

**Comment by mohamed-barakat** [comment]
```
apt-get install julia
```

**Comment by fingolfin** [comment]
Yeah, well, this is Debian/Ubuntu, the masters of chopping up upstream packages and disfiguring them until they are broken beyond repair... e.g. they modify GAP to force it to load w/o smallgroups installed, and when we thought about adding code that would print a warning in this setup that things might be broken, they announced they'd also patch our warning out...

Look for a `julia-dev` package then, they might have moved header files there.

**Comment by mohamed-barakat** [comment]
I see :( I've already tried getting `julia-dev` but `E: Unable to locate package julia-dev`.

Do you have an idea of where to find the ubuntu image Travis uses for building?

**Comment by fingolfin** [comment]
Searching https://packages.ubuntu.com/search?lang=de&keywords=julia&searchon=names suggests that `libjulia-dev` is the name of the package

**Comment by mohamed-barakat** [comment]
This resolves the issue. Thank you very much Max.

**Comment by mohamed-barakat** [comment]
Now I can finally debug the [failing tests](https://travis-ci.com/github/homalg-project/HomalgProject.jl/jobs/336020505) for 4ti2Interface on ubuntu :)
