### ISSUE TITLE
Document ForeignGAP.MPtr

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#471]
I needed [ForeignGAP.MPtr](https://github.com/oscar-system/GAP.jl/blob/992bf34386554eccd7356089fc1bb2729fca5929/src/GAP.jl#L48) in [this code](https://github.com/homalg-project/HomalgProject.jl/blob/master/src/HomalgProject.jl#L82). So maybe it is indeed a good idea to document it.

**Comment by fingolfin** [comment]
`Main.ForeignGAP.MPtr` is a low-level implementation detail that I really don't want to document (beyond source code comments). It's also unclear to me why you need it in that code -- why can't you use its supertype `GAP.GapObj`?

**Comment by mohamed-barakat** [comment]
See https://github.com/oscar-system/GAP.jl/pull/610.
