### ISSUE TITLE
Rename EvalString to something more Julia like

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#473]
We really should rename `EvalString` to a more julia like name. Note that `eval` is already taken and has a special meaning in Julia; but e.g. `evalstr` or `evalgap` or so might be OK.

To allow other code depending on GAP.jl to transition, we could retain an `EvalString` method which invokes the new method but perhaps also prints a deprecation warning.

**Comment by ThomasBreuer** [comment]
I prefer `evalstr`, the GAP context is usually clear because the function will be called as `GAP.evalstr`.
The name change will be part of the revised #472 .
