### ISSUE TITLE
Allow `julia_to_gap(x; recursive=true)`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#475]
Recursive conversion right now works this way:
```
y = GAP.julia_to_gap(x, Val(true))
x = GAP.gap_to_julia(Vector{Any}, y; recursive = true)
```
Using `Val` arguments was (IIRC) meant to be an optimization; I am not sure if it does that, but I *am* sure that it makes it harder to use the code, as the two directions diverse.

So I think we should also allow `julia_to_gap(x; recursive=true)` -- I guess we can achieve with 1-2 lines of added code (plus some more for tests). @ThomasBreuer can you perhaps look into doing that?

On the long run, perhaps that should be the default, and the `Val` usage be removed (but then we need to take care of backwards compatibility; in any case, I see no urgent need).

**Comment by ThomasBreuer** [comment]
@fingolfin Yes, I will do this.
