### ISSUE TITLE
doctest fail with Julia 1.6?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#484]
See https://travis-ci.com/github/oscar-system/GAP.jl/jobs/359229945

This seems annoying, not sure we can do something clever about it

CC @ThomasBreuer

**Comment by fingolfin** [comment]
Perhaps we can use https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Filtering-Doctests to help with this

**Comment by ThomasBreuer** [comment]
In principle, the `doctestfilters` feature seems to solve the problem.
I would prefer the variant where all differences are collected globally, and entered as one list to the function in question (as opposed to the variant where each affected doctest gets such an "annotation").
This works for executing doctests as a part of what `makedocs` does, but it seems not to work for executing doctests as ordinary tests, via `doctest`, see https://github.com/JuliaDocs/Documenter.jl/issues/1364.

(As far as I understand, the failures do not happen with Julia 1.5. I do not see the changed `typeof`/`showarg` outputs in Julia 1.5.0-rc1, but in Julia 1.6.0-DEV.)

**Comment by fingolfin** [comment]
This was fixed in #491
