### ISSUE TITLE
Reduce the overhead for GAP symbol lookup via `GAP.Globals.NAME`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#485]
**UPDATE: The timings I originally posted here were made after `using Oscar`; as I now know, that inflated them; so I update the numbers with fresh ones taken after just `using GAP`.**

The overhead for `GAP.Globals.NAME` is currently quite high:
```julia
using GAP, BenchmarkTools
function test_simple()
  for i = 1:1000000
    x = GAP.Globals.IsAbelian
  end
end
```
Benchmarking this with `BenchmarkTools.jl` gives:
```
julia> @benchmark test_simple()
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     42.138 ms (0.00% GC)
  median time:      42.946 ms (0.00% GC)
  mean time:        43.269 ms (0.00% GC)
  maximum time:     50.586 ms (0.00% GC)
  --------------
  samples:          116
  evals/sample:     1
```

This is indeed quite noticeable; compare this trivial example where we query `IsAbelian` for a group; first we do it "naively", then we cache the value of `GAP.Globals.IsAbelian`.
```julia
using GAP, BenchmarkTools
G = GAP.Globals.CyclicGroup(10)

function test_isabelian_1()
  x = true
  for i = 1:1000000
    x = x && GAP.Globals.IsAbelian(G)
  end
end

function test_isabelian_2()
  f = GAP.Globals.IsAbelian
  x = true
  for i = 1:1000000
    x = x && f(G)
  end
end
```
Here are the timings:
```
julia> @benchmark test_isabelian_1()
BenchmarkTools.Trial:
  memory estimate:  15.26 MiB
  allocs estimate:  1000000
  --------------
  minimum time:     213.316 ms (0.00% GC)
  median time:      218.107 ms (0.00% GC)
  mean time:        220.472 ms (0.77% GC)
  maximum time:     257.289 ms (8.72% GC)
  --------------
  samples:          23
  evals/sample:     1

julia> @benchmark test_isabelian_2()
BenchmarkTools.Trial:
  memory estimate:  15.26 MiB
  allocs estimate:  1000000
  --------------
  minimum time:     158.783 ms (0.00% GC)
  median time:      164.770 ms (0.00% GC)
  mean time:        165.974 ms (0.99% GC)
  maximum time:     183.713 ms (9.34% GC)
  --------------
  samples:          31
  evals/sample:     1
```
So that's a quite noticeable overhead for a rather trivial operation.

The other thing to note is that the calls to `IsAbelian` themselves are atrociously slow when compared to GAP, I'll file a separate issue on that.

**Comment by fingolfin** [comment]
OK, so I am really confused by this and hope somebody (e.g. @rbehrends) can help me understand this: the above timings vary wildly depending on whether I just load GAP.jl; just load Oscar.jl; or load first GAP.jl and then Oscar.jl. (In each of the three cases, I copy&pasted the code for `test_simple()` into my session; I am using Julia 1.4.2 on macOS, GAP 0.4.2 and the latest Oscar.jl `master` branch)

1. In a fresh Julia session, after just `using GAP, BenchmarkTools`:
```
julia> @btime test_simple()
  38.616 ms (0 allocations: 0 bytes)
```

2. In a fresh Julia session, after just `using Oscar, BenchmarkTools`:
```
julia> @btime test_simple()
  181.802 ms (0 allocations: 0 bytes)
```

3. In a fresh Julia session, after just `using GAP, Oscar, BenchmarkTools`:
```
julia> @btime test_simple()
  377.012 ms (0 allocations: 0 bytes)
```

So loading GAP then Oscar introduces a factor 10 there! While just loading Oscar (not loading GAP before) "only" causes a factor ~4.7 slow down.

What is going on there?

**Comment by fingolfin** [comment]
I guess type (in)stability is partially (if not mostly) relevant for the overhead. However, I still don't understand how that might explain the slow down when Oscar is loaded. Huh

**Comment by rfourquet** [comment]
On my machine with Julia 1.4.1, I observe these timings for `test_simple`: 
* `GAP` loaded: 52ms
* `Oscar` loaded: 438ms
* `GAP` and `Oscar` loaded: 445ms

So no difference between the last two timings basically.

On 1.6 the difference appears less important: 52ms with `GAP` and "only" 242ms with `Oscar`. In any case, I don't see what could cause this difference.

**Comment by fingolfin** [comment]
Just to verify/clarify: `using Oscar` and `using Oscar, GAP` behave the same; it is only with `using GAP, Oscar` (i.e. really loading GAP *before* Oscar) that I see a difference. Anyway, to make sure this is not just Mac specific, I re-run the tests on a Linux machine. For all tests, I used a dedicated Julia project with the following packages installed (I had to dev Polymake and Nemo, otherwise Polymake didn't build with GCC 10 on the test machine; I did not have time to investigate, and deving was the quickest solution):
```
  [6e4b80f9] BenchmarkTools v0.5.0
  [1f15a43c] CxxWrap v0.10.2
  [c863536a] GAP v0.4.2 [`../../GAP.jl`]
  [3e1990a7] Hecke v0.8.3
  [2edaba10] Nemo v0.17.5 [`../../Nemo.jl`]
  [f1435218] Oscar v0.4.0 [`..`]
  [d720cf60] Polymake v0.4.2 [`../../Polymake.jl`]
  [bcd08a7b] Singular v0.3.1
```

With Julia 1.4.2 I observed the following results for `@btime test_simple()`, which is similar to what I saw on macOS (except there I tested fewer package combinations):
- `using GAP`: 48 ms
- `using Oscar`: 219 ms
- `using CxxWrap; using GAP`: 238 ms
- `using Polymake; using GAP`: 452 ms
- `using Singular; using GAP`: 253 ms
- `using Hecke; using GAP`: 52 ms
- `using Oscar; using GAP`: 210 ms
- `using GAP; using CxxWrap `: 265 ms
- `using GAP; using Polymake `: 412 ms
- `using GAP; using Singular `: 243 ms
- `using GAP; using Hecke `: 46 ms
- `using GAP; using Oscar`: 400 ms

On the same machine I re-run the tests with Julia 1.5.0-rc1 and got this:
- `using GAP`: 48 ms
- `using Oscar`: 401 ms
- `using CxxWrap; using GAP`: 285 ms
- `using Polymake; using GAP`: 518 ms
- `using Singular; using GAP`: 277 ms
- `using Hecke; using GAP`: 46 ms
- `using Oscar; using GAP`: 403 ms
- `using GAP; using CxxWrap `: 290 ms
- `using GAP; using Polymake `: 501 ms
- `using GAP; using Singular `: 271 ms
- `using GAP; using Hecke `: 52 ms
- `using GAP; using Oscar`: 421 ms

Some observations:
- Julia 1.5 got slower in various aspects
- Loading Hecke before or after GAP makes no difference (other than fluctuation due to noise on the test machine)
- loading CxxWrap.jl, Singular.jl, Polymake.jl or Oscar.jl, cause a massive slowdown; for Polymake it is even worse than what Oscar does (even though Oscar loads Polymake?!?)
- so that makes me wonder about CxxWrap... I know that it uses the GC callbacks we added; and I know that at some point our GC callbacks caused a substantial performance overhead (see issue #266)

**Comment by rbehrends** [comment]
I tested with Julia 1.4.1 and got somewhat different results, matching those of Rafael in that the about 10-fold difference was made by using Oscar, both with and without GAP.

Some profiling indicates that the extra time is spent in `jl_typemap_level_assoc_exact()`, called from `jl_lookup_generic_()`.  For the slow case it is being called a lot, for the fast case it doesn't even seem to show up on the profile. This would indicate the problem has to do with the global call cache so that each time the code resorts to searching the method table.

**Comment by fingolfin** [comment]
I sped up the basecase for `@btime test_simple()`, from 48ms to 26ms,  via 1d339eacb2a3598f3830c9a9940cad1f3ef7ab4d (by making `GAP.Globals` const... oops). Unfortunately it doesn't really help when `CxxWrap.jl` is loaded.

**Comment by fingolfin** [comment]
PR #495 should remove the slowdown when CxxWrap.jl is loaded (see also https://github.com/JuliaInterop/CxxWrap.jl/issues/258).

Together with the improvements already made, I think there is not much we can do here with reasonable effort... well, one could try again something which we did in the past but then discarded as it was slower back then: namely, the GAP kernel function `GVarName` maps identifiers to "gvar" ids, which are simply unsigned integers (which are indices into a big array of "global variables"). Using such a "gvar" one can relatively quickly get or set the corresponding global variable. This is what the GAP interpreter internally uses. We did use these as well in the past, using an `IdDict` to map Julia symbols to "gvar" ids. But this was *slower* than what we do now (which is to just pass the symbol resp. the underlying C string, to GAP), as GAP's lookup table for identifier strings is quite optimized already.

Now, if we could somehow tweak this so that the Julia compiled understands that it is allowed to hoist that lookup of the "GVarName" out of loops, we could become competitive to native GAP. Alas, I am not sure how one could do that... Perhaps if there was a way to mark a `ccall` as "pure" (i.e. it will always return the same value)... Alternatively, a macro could be written which takes a function expression as argument; scans it for all occurrences of `GAP.Globals.FOO`; then transforms the code to precompute the "gvar" ids and then use them in place of `GAP.Globals.FOO`... but that sounds like a lot of effort for a tiny gain, and anyway this kind of transformation is easy to perform manually.

**Comment by fingolfin** [comment]
I just realized there is @pure so I'll give that a try

**Comment by ThomasBreuer** [comment]
@fingolfin If I understand your statement about the costs of accessing variables from `GAP.Globals` right then we should emphasize in the documentation that one should reduce such calls, in particular, that it is advisable to fetch a GAP function once outside a loop, instead of fetching it in each iteration.
There are a few places in the code of GAP.jl which can be improved accordingly.

**Comment by fingolfin** [comment]
@ThomasBreuer agreed on all accounts
