### ISSUE TITLE
Find a way to merge GapObj / MPtr after all, or at least mitigate the performance penalty introduced by their split

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#488]
Consider this test code (which also covers the issues reported in #485 and #486):
```julia
using Oscar, BenchmarkTools

const reps = 1000000

G = cyclic_group(10)

function test_isabelian_0()
  x = true
  for i = 1:reps
    x = x && isabelian(G)
  end
end

function test_isabelian_1()
  x = true
  for i = 1:reps
    x = x && GAP.Globals.IsAbelian(G.X)
  end
end

function test_isabelian_1b()
  x = true
  g = G.X
  for i = 1:reps
    x = x && GAP.Globals.IsAbelian(g)
  end
end

function test_isabelian_2()
  f = GAP.Globals.IsAbelian
  x = true
  for i = 1:reps
    x = x && f(G.X)
  end
end

function test_isabelian_2b()
  f = GAP.Globals.IsAbelian
  x = true
  g = G.X
  for i = 1:reps
    x = x && f(g)
  end
end

function test_isabelian_2c_inner(f, g)
  x = true
  for i = 1:reps
    x = x && f(g)
  end
end
function test_isabelian_2c()
  f = GAP.Globals.IsAbelian
  g = G.X
  test_isabelian_2c_inner(f, g)
end
```
Then I currently get these timings (note in particular the last three):
```
julia> @btime test_isabelian_0()
  401.775 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1()
  421.117 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1b()
  387.460 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2()
  190.650 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2b()
  161.666 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2c()
  152.468 ms (1000000 allocations: 15.26 MiB)
```

Before discussing the numbers, a brief detour: very annoyingly, if I repeat the test with PR #487 applied, which is meant to improve performance, things actually get slower *sigh*:
```
julia> @btime test_isabelian_0()
  448.007 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1()
  464.477 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1b()
  417.475 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2()
  217.320 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2b()
  193.294 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2c()
  174.803 ms (0 allocations: 0 bytes)

```

Anyway: The problem I actually wanted to discuss in this issue is the following: In `struct GAPGroup` we have a member `X::GapObj`. Now, X really is always of type `ForeignGAP.MPtr`, the only subtype of `GapObj`. But as you may know, we cannot use `ForeignGAP.MPtr` in the top level of our modules, as that would break precompilation: the type `ForeignGAP.MPtr` is injected at runtime by the GAP kernel. We introduce the supertype `GapObj` precisely so that we could write code without using `ForeignGAP.MPtr`. For function signatures, that's all fine and well. But for structs, it has the effect that when one writes `G.X` in the examples above, Julia cannot determine the concrete type at compile time, only at runtime; it hence cannot specialize the call. In `test_isabelian_2b` we partially mitigate the issue by hoisting `G.X` out of the loop; this way the compiler can at least determine that for each invocation of `f`, the same method will be used. Finally in `test_isabelian_2c` we use a standard trick and move the actual computation into a separate function, and ensure the types of its arguments are fully known at call time; by crossing a function boundary, we thus allow the JIT to kick in and fully optimize (possibly inline) the function call.

While this works, keeping this trick in mind is a serious burden; also, even if we get this "right" in Oscar.jl, then users who write their own code may very well be bitten by this.

One tricky to overcome this is to parametrize types like `GAPGroup` and use something like `struct GAPGroup{T <: GapObj}   X::T ... end`. But this has its own drawbacks, not the least of which is that type names get rather ugly.

I am not sure if there is any way to overcome this. We may need to discuss this with the Julia core devs at some point?

**Comment by rfourquet** [comment]
I don't know of a solution, but just wanted to mention that the timing differences are more dramatic on master than on 1.4, and that type annotations have the same effect as using a function barrier:
```
function test_isabelian_2d()
    f = GAP.Globals.IsAbelian::ForeignGAP.MPtr
    x = true
    for i = 1:reps
        x = x && f(G.X::ForeignGAP.MPtr)
    end
end
```
Also I made `G` constant here for the timings. On 1.4 I get:
```
julia> @btime test_isabelian_0()
  765.697 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1()
  777.529 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1b()
  768.199 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2()
  233.929 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2b()
  236.938 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2c()
  208.670 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2d()
  209.135 ms (1000000 allocations: 15.26 MiB)
```
On master (v1.6):
```
julia> @btime test_isabelian_0()
  993.897 ms (7000000 allocations: 106.81 MiB)

julia> @btime test_isabelian_1()
  969.913 ms (7000000 allocations: 106.81 MiB)

julia> @btime test_isabelian_1b()
  971.392 ms (7000000 allocations: 106.81 MiB)

julia> @btime test_isabelian_2()
  684.071 ms (7000000 allocations: 106.81 MiB)

julia> @btime test_isabelian_2b()
  672.720 ms (7000000 allocations: 106.81 MiB)

julia> @btime test_isabelian_2c()
  100.154 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2d()
  100.111 ms (1000000 allocations: 15.26 MiB)
```

**Comment by fingolfin** [comment]
Some updates (using Julia 1.4.2): With the current GAP.jl master, I now get these improved timings:
```
julia> @btime test_isabelian_0()
  200.640 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1()
  209.204 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1b()
  182.815 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2()
  202.011 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2b()
  172.590 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2c()
  161.353 ms (1000000 allocations: 15.26 MiB)
```

With PR https://github.com/oscar-system/GAP.jl/pull/487 we see a clear improvement by a factor of 5-10:
```
julia> @btime test_isabelian_0()
  48.592 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1()
  56.946 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1b()
  34.899 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2()
  48.550 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2b()
  26.800 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2c()
  15.909 ms (0 allocations: 0 bytes)
```

If we turn `G` into a `const` var a suggested by @rfourquet we get even better results for all but the last two tests.... With GAP.jlmaster:
```
julia> @btime test_isabelian_0()
  185.928 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1()
  187.145 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_1b()
  184.269 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2()
  175.046 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2b()
  184.193 ms (1000000 allocations: 15.26 MiB)

julia> @btime test_isabelian_2c()
  160.569 ms (1000000 allocations: 15.26 MiB)
```
With the GAP.jl PR:
```
julia> @btime test_isabelian_0()
  38.280 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1()
  34.940 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_1b()
  34.916 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2()
  27.351 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2b()
  28.347 ms (0 allocations: 0 bytes)

julia> @btime test_isabelian_2c()
  15.998 ms (0 allocations: 0 bytes)
```

So all in all, the performance gap (no pun intended) has been reduced. But even in the best of the four scenarios above (i.e. the last) we still have a factor > 2 between test 0 and test 2c.

**Comment by fingolfin** [comment]
Using the `@generated` (as discussed here: https://github.com/oscar-system/Oscar.jl/issues/128#issuecomment-750457220) plus merging types GapObj and MPtr, we can get close to "optimal" performance.
