### ISSUE TITLE
GAP.Globals.Display once a GAP error has occured

### ISSUE THREAD

**Issue by zickgraf** [oscar-system/GAP.jl#516]
Consider the following code and output:
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> using GAP
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-julia64-kv7-v1.5
 Configuration:  gmp 6.2.0, Julia GC, Julia 1.5.1, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.dev, PrimGrp 3.4.0, SmallGrp 1.4.1, TransGrp 2.0.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

julia> GAP.Globals.Display( g"test1" )
test1

julia> GAP.Display( g"test2" )
test2

julia> GAP.evalstr( "error" )
ERROR: Error thrown by GAP: Error, Variable: 'error' must have a value

Stacktrace:
 [1] error_handler() at .julia/packages/GAP/tkivN/src/GAP.jl:157
 [2] evalstr_ex at .julia/packages/GAP/tkivN/src/ccalls.jl:36 [inlined]
 [3] evalstr(::String) at .julia/packages/GAP/tkivN/src/ccalls.jl:63
 [4] top-level scope at REPL[4]:1
 [5] run_repl(::REPL.AbstractREPL, ::Any) at /build/julia/src/julia-1.5.1/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288

julia> GAP.Globals.Display( g"test3" )

julia> GAP.Display( g"test4" )
test4

julia>

```
The string `test3` is not printed. In fact, nothing seems to be printed using `GAP.Globals.Display` after an error has occured. `GAP.Display` seems to work fine.

A related question we are interested in: Which stream is `Display` outputting to? We would like to turn the print formatting off for this stream as we did in #513.

**Comment by ThomasBreuer** [comment]
@zickgraf Thanks for this report.

I have played around more with this problem (in Julia 1.4.0).
After an error, as shown above, GAP's `View`, `Print`, `Display` do all not print anything to the screen.
However, these functions seem not to work properly also without an error; for example, I get the following.

```
julia> using GAP
[...]

julia> GAP.Globals.Display( GAP.evalstr( "10^150" ) )
100000000000000000000000000000000000000000000000000000000000000000000000000000\
0000000000000000000000000000000000000000000000000000000000000000000000000

julia> GAP.Globals.Print( GAP.evalstr( "10^150" ) )
100000000000000000000000000000000000000000000000000000000000000000000000000000\

julia> GAP.Globals.View( GAP.evalstr( "10^150" ) )
0000000000000000000000000000000000000000000000000000000000000000000000000
 10000000000000000000000000000000000000000000000000000000000000000000000000000\

julia> GAP.Globals.View( GAP.evalstr( "10^150" ) )
000000000000000000000000000000000000000000000000000000000000000000000000001000\
000000000000000000000000000000000000000000000000000000000000000000000000000000\

julia> GAP.Globals.View( GAP.evalstr( "10^150" ) )
000000000000000000000000000000000000000000000000000000000000000000000100000000\
000000000000000000000000000000000000000000000000000000000000000000000000000000\

julia> GAP.Globals.Display( GAP.evalstr( "10^150" ) )
0000000000000000000000000000000000000000000000000000000000000000
100000000000000000000000000000000000000000000000000000000000000000000000000000\
0000000000000000000000000000000000000000000000000000000000000000000000000

```
Can you reproduce this behaviour?

Concerning the question to which stream the output of `GAP.Globals.Display` is sent:
GAP gives the advice (see `?SetPrintFormattingStatus`) to call `SetPrintFormattingStatus( "*stdout*", false )` in order to switch off the formatting. This works for `Print`, `Display`, etc. *in GAP*, but apparently it *does not help* when GAP is called from Julia.
Is this a feature or another bug?

**Comment by zickgraf** [comment]
> Can you reproduce this behaviour?

Not exactly, but in general yes. The result seems to depend on the width of the terminal.

Observation: If I `Print` a string of length shorter than my terminal width, I get no output at first, but the output is shown later once something exceeds the width of my terminal:
```
julia> GAP.Globals.Print( GAP.evalstr( "1" ) )

julia> GAP.Globals.Print( GAP.evalstr( "2" ) )

julia> GAP.Globals.Print( GAP.evalstr( "3" ) )

julia> GAP.Globals.Print( GAP.evalstr( "10^150" ) )
123
100000000000000000000000000000000000000000000000000000000000000000000000000\
000000000000000000000000000000000000000000000000000000000000000000000000000\

julia>
```
I assume something buffers the output until some condition (newline?) is reached. If I immediately print a newline, everything works as expected:
```
julia> GAP.Globals.Print( GAP.evalstr( "\"1\\n\"" ) )
1

julia>
```

> GAP gives the advice (see ?SetPrintFormattingStatus) to call SetPrintFormattingStatus( "*stdout*", false ) in order to switch off the formatting. This works for Print, Display, etc. in GAP, but apparently it does not help when GAP is called from Julia.
> Is this a feature or another bug?

I can confirm that it does not work from Julia, not even in `GAP.prompt()`. I assume there is some more magic happening in the background.
