### ISSUE TITLE
ordering of initialization steps

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#518]
GAP.jl's initialization depends on libgap's `GAP_Initialize`, which runs GAP's initialization.
In particular, autoloading GAP packages is part of this process.
Only afterwards, GAP.jl loads the GAP package JuliaInterface.

As soon as one wants to autoload JuliaInterface (not very likely) or a GAP package that depends on JuliaInterface (might become more likely), calling `using GAP` runs into the following problem.
```
WARNING: using GAP.GAP in module Main conflicts with an existing identifier.
ERROR: importing GAP into Main conflicts with an existing identifier
```
This happens after the execution of the `__init__` function of GAP.jl.

Do we have to forbid autoloading JuliaInterface and related packages?

**Comment by ThomasBreuer** [comment]
Here is another instance of the same problem:
When one starts GAP such that the name of an input file belongs to the command line then this file will be read before the initialization process has loaded JuliaInterface.
Thus one cannot use the GAP-Julia integration in the input file.
(Explicitly loading JuliaInterface in the input file leads to the above error, and GAP crashes.)

**Comment by fingolfin** [comment]
So we really should load JuliaInterface earlier.

We discussed this a bit in a Jitsi meeting. I stumbled over related issues when working on the `initialize` code -- part of the problem there was that GAP starts by reading `init.g`, which does a lot, including the processing of the command line arguments -- in fact we might end up quitting in there, if the user passed a file that quits.

One trick I employed to deal with this was to insert extra arguments to be passed to `GAP_Initialize`. We could try the same for loading JuliaInterface, and add the equivalent of `-c LoadPackage("JuliaInterface")` to the *start* of the `argv` vector. Of course that's yet another hack, but it should at least work right now. We can then work on a "proper" solution on the GAP side for future GAP releases.

**Comment by ThomasBreuer** [comment]
@fingolfin I understand GAP's `lib/init.g` as follows.
1. The steps until the user preferences in `gap.ini` get evaluated seem to be harmless in the sense that the GAP-Julia integration is not affected.
2. Then `AutoloadPackages` is called. Here JuliaInterface may be requested (perhaps indirectly) for loading.
3. Then some more GAP internal initializations happen. The only part that  is relevant for Julia is that the `gaprc` file may already try to use the Julia integration (set some variables, read some user files, ...).
4. Then the files mentioned in the command line (`GAPInfo.InitFiles`) are read.

At the moment, I see the following two issues.

- First, GAP.jl tries to inform JuliaInterface about the fact that GAP.jl wants to control the loading process by setting the GAP variable `__JULIAINTERNAL_LOADED_FROM_JULIA`. However, this is done via a `-c` command line option (stored in `GAPInfo.InitFiles`), and this gets executed only in step 4, which is too late for loading JuliaInterface already in step 2.

- Second, when the user starts GAP with Julia integration, a file mentioned in the command line (`GAPInfo.InitFiles`) is currently read too early, because GAP.jl's initialization is not yet finished when step 4 is executed; thus one can see subtle differences between the situations when a file is read via a command line option or when a file is read at the first GAP prompt.

For the first issue, we could try to set the GAP variable `__JULIAINTERNAL_LOADED_FROM_JULIA` before step 2, but how can we achieve this?

For the second issue, either it would be necessary to make sure that all assignments from GAP.jl's `__init__` happen before libgap's `GAP_Initialize` is called, or we should tell GAP to ignore `GAPInfo.InitFiles`, and then deal with the entries in GAP.jl, at the end of `__init__`. (The latter looks easier.)

**Comment by fingolfin** [comment]
We could set the kernel variable `SyLoadSystemInitFile` to 1, to skip the loading of `init.g` by the kernel. Then we can do stuff between initializing the GAP kernel, and reading `init.g` (which we'd then have to do ourselves, but that shouldn't be an issue). In particular we can set `__JULIAINTERNAL_LOADED_FROM_JULIA` sooner and in a cleaner fashion.

To get `JuliaInterface` loaded as part of `AutoloadPackages`, we could add it to `GAPInfo.Dependencies.NeededOtherPackages`; while that is immutable, one can do it via `GAPInfo.Dependencies := rec(NeededOtherPackages:=[ ... ]);`. Of course the code doing that must be inserted at the right place, after `system.g` is loaded. One way to achieve *that* would be to provide our own `system.g` in our own GAP root which comes before the "main" GAP root, so that our `system.g` is picked up; "our" system.g could then read the real one, and afterwards inject `JuliaInterface`. Of course that's rather a hack; cleaner would be to offer some kind of hook that's executed at the right place. Something like "if file`extra_init.g` is present in a GAP root, read it".

**Comment by ThomasBreuer** [comment]
@fingolfin Good ideas, I will try them.

**Comment by ThomasBreuer** [comment]
@fingolfin I have made some experiments.

Skipping the loading of GAP's `init.g` would help only with manipulate some of GAP's kernel variables before reading `init.g`; I would not like to do this, and I also think this is not necessary.

All we need is to interfere after GAP has read `system.g`, that is, when `GAPInfo` has been set up; in particular, the command line has been moved from the kernel to the library.
I propose a new GAP command line option `--systemfile` that allows one to specify a GAP file that is read after `system.g`. This file then contains code to
1. set the variable `__JULIAINTERNAL_LOADED_FROM_JULIA`,
2. add `JuliaInterface` to `GAPInfo.Dependencies.NeededOtherPackages` (when the variable from 1. is set, the package can be loaded already when the other packages get loaded),
3. change `GAPInfo.InitFiles` such that files are *not* read during GAP's initialization (`GAP_Initialize`) but after GAP.jl has completed its initialization (then hopefully the differences between reading files via the comand line and reading files at the GAP prompt disappear), and
4. perform other changes in GAP which simplify some code.

Well, this is what I thought, but it does not really work yet. In "stand-alone" mode, when one calls GAP with the `testall.g` file of JuliaInterface, I get `Error, UndefVarError: GAP not defined` errors from Julia.
Reading `testall.g` later than we did up to now should make things easier, but apparently the GAP code runs in a wrong context now. (Reading `testall.g` from the GAP prompt is no problem.)

The current state of my experiments (for the sake of simplicity only concerning 1. and 2.) is given by the pull requests #548 for GAP.jl and gap-system/gap/pull/4160 for GAP.

**Comment by ThomasBreuer** [comment]
@fingolfin I think the situation is as follows:
Before the changes I had tried, calling `/.../gap.sh testall.g` starts Julia and calls `using GAP`, with `testall.g` on the GAP command line.
Then GAP.jl calls libgap's GAP_Initialize, which reads `testall.g` before `__JULIAINTERNAL_LOADED_FROM_JULIA` gets set.
In `testall.g`, the package `JuliaInterface` gets loaded, which does not find `__JULIAINTERNAL_LOADED_FROM_JULIA`, thus it executes `JuliaEvalString( "Base.MainInclude.include(Base.find_package(\"GAP\"))" )`.
Then the GAP tests are executed without problems.
Afterwards, the GAP session is left via `FORCE_QUIT_GAP(1);`.

If we do *not* exit from the GAP session in this situation, GAP.jl's initializations continue, and after `__init__` has finished, Julia wants to make the new module available in `Main` --but the variable is already there, and we get a Julia error.

The problem seems to be that `using GAP` binds the module in `Main` after all these functions have been executed. Only afterwards it is safe to access the `GAP` module.
But when some GAP files on the command line start using the Julia integration, we try to do this already before the `__init__` function is done.

**Comment by fingolfin** [comment]
OK, I had completely forgotten about the `JuliaEvalString( "Base.MainInclude.include(Base.find_package(\"GAP\"))" ) ` hack -- it all now makes sense, and I think this also explains issues #419 and #461 !

What happens is that while we are in the middle of creating the Julia module `GAP` we start reading `src/GAP.jl` *again*, and create another module, let's call it `GAP'`; and then we assign that to the global Julia variable GAP, and use it.

But we really created a *second* module; and also a second type `GapObj` etc. As long as only one or the other is "visible" this is fine, but in #419 we ended up testing MPtr derived from the one `GapObj` for being a subtype of the other `GapObj`, hence the error.

Also, one module is known as "GAP" the other as "Main.GAP", hence issue #461 

Anyway: these days we *always* load Julia first, then GAP. So I think we can get rid of, and hence made PR #557 (which seems to work for me, but let's see what the CI tests make out of it).
