### ISSUE TITLE
Feature request: add more Julia conversion constructors, e.g. for `Set` 

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#529]
Just came across this code: `Set{Int}(GAP.gap_to_julia(GAP.Globals.MovedPoints(H.X)))` would be nice if one could rewrite this as e.g. `Set{Int}(GAP.Globals.MovedPoints(H.X))`

**Comment by rfourquet** [comment]
Can iteration be defined on `GAP.Globals.MovedPoints(H.X))` ? It would be enough for the `Set`/`Set{Int}` constructors to accept it.

**Comment by ThomasBreuer** [comment]
Concerning iteration: The return value of `GAP.Globals.MovedPoints` is a GAP list. Julia just sees that it is a GAP object. Without more type information on the Julia side, defining iteration for this object would require to define iteration for all GAP objects. This would be possible, by delegating to an iterator on the GAP side, but this might lead to "misuses" in the sense that this feature is likely to introduce  overhead. (Marek has once brought up this argument.)

**Comment by ThomasBreuer** [comment]
I understand the request for a `Set{T}` method in such a way that the functionality of GAP's function `Set` gets called;
the argument can be any GAP list or collection, for example a group object.
(In the case of a GAP domain, the code should call `Elements` in order to avoid creating additionally a mutable GAP list.)
As usual, the default should be recursive conversion.

What is meant with "e.g.", that is, which other constructors shall be put on the wish list?

**Comment by fingolfin** [comment]
Whether it calls `Set` or `AsSet` (for which `Elements` is a synonym) or some Julia functions to remove duplicates doesn't matter from my POV. But the user visible result would be similar to what one gets when using a Julia vector as input:
```
julia> Set{Int}([1,2,4,1])
Set{Int64} with 3 elements:
  4
  2
  1
```
However, this all comes with a caveat: it is OK for `Set{T}` where T is a regular Julia type such as Int, BigInt, String, etc;  what won't work well in general is `Set{GapObj}`, because we don't (and can't, really) provide reasonable hashing for `GapObj`. But that's OK: this is IMHO mostly a convenience functionality. It's OK if it doesn't work well in every possible usecase, just in common ones.

For the "e.g." I was thinking about `BitSet`. Perhaps also `IdSet` and `IdDict`? And, well, other standard container types I might now aware and that we do not yet support.

**Comment by ThomasBreuer** [comment]
@fingolfin Julia `Set`s of `GapObj`s are really problematic.
Already without a `Set{T}` constructor for a `GapObj`, we run into logical problems, as follows. (One may need several attempts in order to reproduce this.)
```
julia> s1 = Set{Any}([GAP.evalstr("()"), GAP.evalstr("(1,2)")])
Set{Any} with 2 elements:
  GAP: (1,2)
  GAP: ()

julia> s2 = Set{Any}([GAP.evalstr("()"), GAP.evalstr("(1,2)")])
Set{Any} with 2 elements:
  GAP: ()
  GAP: (1,2)

julia> s1 == s2
false
```

**Comment by fingolfin** [comment]
Regarding the quirk with two non-equal sets that should be equal: most likely (I am not at my computer so can't check right now) that's because we don't provide a hash function for GapObj, so a default one is used, which is wrong as we implement a method for ==. Solution: add one; the only "legal" way to do that Is to use a constant one, say 0. Yes this kills performance of Set{GapObj} but (a) that can't be helped im general and (b) I really don't care :-)

Because I am really not interested in Set{Any} nor Set{GapObj}. I am however interested in Set{T} where T is a "regular" Julia type, or even more limited: constructed from combinations of basic types like Int, String, Array, Set, BitSet.

**Comment by rfourquet** [comment]
Sorry for the naive question: what is the main difficulty with providing a `hash` method for GAP objects? Could this be done incrementally by defining on the Julia side `hash` methods based on the GAP type (inspecting the values from Julia)? This would probably involve a big if/elseif chain (or tree?), so I'm not sure how practical this would be. Would it make sense to add hashing methods on the GAP side?

**Comment by ThomasBreuer** [comment]
@fingolfin So there are two issues.
The first is that some results are wrong because of the missing `hash` method(s); I have created the pull request #536 for fixing this bug.
The second is to make `Set` available for GAP objects, see pull request #537

**Comment by fingolfin** [comment]
@rfourquet in general it is impossible to define *useful* valid hash functions for GAP objects that satisfy the requirement that equality of objects implies equal hashes.  Here with "useful" I mean that the function must be computable fast enough and must also be better than a constant function. This is because in GAP things can change their internal representation (so you can't just hash some bytes somewhere) and because things in radically different representation are treated as equal.

Of course there are exceptions; e.g. integers, rationals and functions could be hashed. And with some reasonable efforts also e.g. permutations (there is of course already code for all that on the GAP side). (All that of course only assuming that one is willing to bet on the user not breaking the contract by e.g. defining a custom permutation representation which compares equal to "regular" GAP permutations but does not provide compatible hashing. But I'd be willing to make that assumption)

But forget about "useful" hashing for more interesting things, like vectors, matrices, groups, etc.

So while one can improve on `hash(x::GapObj) = 0` eventually, this is not useful in general. At the same time, I don't really think it's of a concern here, nor for Oscar, so let's not waste time on that now (if somebody has a concrete application where it matters, we can still look into changing this for the specific objects types in question).

**Comment by rfourquet** [comment]
Thanks @fingolfin for expanding on this. I would personally be curious eventually to look closer into that to understand better the difficulties, but I also understand this is not a priority.

But then is it really useful to implement a `Set` constructor for GAP objects? (besides for collection of objects for which we can provide non-trivial hashing)
If they all hash equal, a `Set` will be strictly worse than a `Vector` (i.e. the objects will be stored in a vector internal to `Set`, with "holes", and will be looked up with a linear search). So providing a `Set` constructor breaks some promise that you have efficient lookup. I saw in @ThomasBreuer's PR that GAP has an `HasSet` function, which presumably uniquifies the elements, before storing them in a set: couldn't we instead provide a `Base.unique` method then? (something like `Base.unique(x::GapObj) = GAP.Globals.AsSet(x)`)

**Comment by ThomasBreuer** [comment]
@rfourquet See the initial comment of this issue: The main idea is that often one deals with GAP lists of integers, or lists of lists of integers, for which it is convenient to map them to Julia `Set`s on request.

**Comment by ThomasBreuer** [comment]
@rfourquet Thanks for the hint about `unique`. This function corresponds to GAP's `DuplicateFreeList`, which is used mainly in situations where the entries can be compared for equality but no ordering for them w.r.t. `<` needs to be defined (and hence GAP cannot use binary search).
GAP's `AsSet( obj )` assumes that the entries of the returned list can be compared with `<`, and the result is a sorted list. (And this list is stored in `obj` whenever this is possible, for example if `obj` is a group object.)

**Comment by rfourquet** [comment]
> The main idea is that often one deals with GAP lists of integers,

Ok makes sense. Maybe in your PR, you could add a warning that this is the intended use-case, and that for objects in general, this will be inefficient?

> GAP's AsSet( obj ) assumes that the entries of the returned list can be compared with <, and the result is a sorted list.

Ok, this is semantically equivalent to Julia's `unique!(sort(obj))` ? And this means that your implementation for `Set` constructor will work only for `<`-comparable objects?

> (And this list is stored in obj whenever this is possible, for example if obj is a group object.)

So the `Set` constructor will be mutating ? This looks like an unexpected side effect, but maybe this is irrelevant here?

**Comment by ThomasBreuer** [comment]
@rfourquet Thanks.
- Yes, I will add a disclaimer to the documentation of the `Set` method.
- If the elements in the GAP object `obj` are not `<`-comparable in GAP then calling `Set{T}(obj)` in Julia will make sense only if `T` is `Any` or `GapObj`, which is not very useful, as @fingolfin wrote. For the sake of completeness, I can modify the code accordingly.
- Concerning the question of mutating: Many calls to GAP functions have the side-effect to set some flags or some newly computed information in the objects, even if many of these objects are regarded as immutable by GAP. In this sense, this side-effect can be regarded as expected from GAP's point of view.

**Comment by rfourquet** [comment]
@ThomasBreuer thanks for the clarifications!

**Comment by fingolfin** [comment]
The bit about objects being mutated by GAP at all kinds of possibly unexpected times is one of the various difficulties with providing useful hashing.

But I think there is a misunderstanding here: Yes, `Set{GapObj}` is not very useful for all the named reasons. But this is really about allowing conversions like `Set{Int}(gap_list_of_integers}`, or similar for `Set{String}` or `Set{Vector{Int}}` etc.. I guess we could try to "forbid" `Set{T} where T<:GapObj` (e.g. by adding such a constructor which then only throws an error), but at this point, that seems premature to me?

**Comment by ThomasBreuer** [comment]
@fingolfin Just for  curiosity: In which sense are objects of the type `Set{GapObj}` worse than objects of the type `Set{Any}` whose elements are `GapObj`s?
(We cannot forbid the creation of the latter kind of objects.)

**Comment by rfourquet** [comment]
> But this is really about allowing conversions like Set{Int}(gap_list_of_integers}, or similar for Set{String} or Set{Vector{Int}}

I was assuming that the main point of defining a `Set` constructor vs. just defining iteration was that it's more efficient in general to uniquify the elements of the collection on the GAP side (via `Globals.AsSet(obj)`), in particular as hashing objects on the Julia side doesn't work well (cf. the trivial `hash` method recently added). But if the use-case is objects which map well to Julia objects, using iteration as a general approach could be good enough?

Rereading this thread, I was wondering about @ThomasBreuer's [comment](https://github.com/oscar-system/GAP.jl/issues/529#issuecomment-703523895):

> This would be possible, by delegating to an iterator on the GAP side, but this might lead to "misuses" in the sense that this feature is likely to introduce overhead.

So I made an experiment (#538) to check this assumption of overhead, and it actually might not be always the case.

**Comment by fingolfin** [comment]
From my POV this is resolved. Of course there might be more things we want to add, but we'll do that as we encounter the need (alternatively, we'll log issues which explicitly describe what is needed/missing)
