### ISSUE TITLE
Fix convert(GapObj, big(2)^100)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#531]
With the current GAP.jl master, I observe this:
```
julia> convert(GapObj, big(2)^100)
ERROR: MethodError: no method matching julia_to_gap(::BigInt; recursive=false)
Closest candidates are:
  julia_to_gap(::BigInt) at /Users/mhorn/.julia/packages/GAP/7w7Vl/src/julia_to_gap.jl:56 got unsupported keyword argument "recursive"
  julia_to_gap(::Integer) at /Users/mhorn/.julia/packages/GAP/7w7Vl/src/julia_to_gap.jl:36 got unsupported keyword argument "recursive"
  julia_to_gap(::Any, ::Val{Recursive}) where Recursive at /Users/mhorn/.julia/packages/GAP/7w7Vl/src/obsolete.jl:10 got unsupported keyword argument "recursive"
  ...
Stacktrace:
 [1] convert(::Type{GapObj}, ::BigInt; recursive::Bool) at /Users/mhorn/.julia/packages/GAP/7w7Vl/src/convert.jl:70
 [2] convert(::Type{GapObj}, ::BigInt) at /Users/mhorn/.julia/packages/GAP/7w7Vl/src/convert.jl:70
 [3] top-level scope at REPL[2]:1
```

**Comment by ThomasBreuer** [comment]
The error appears because no method for `GAP.julia_to_gap( 1, recursive = false )` is available.
Pull request #532 should fix this.

However, does this solve the problem with `convert(GapObj, 1)`?
(The result of the conversion cannot be a `GapObj`.)

**Comment by fingolfin** [comment]
OK, 1 is a special case in this regard; I've changed the issue to talk about `convert(GapObj, big(2)^100)` to avoid this additional complication.

**Comment by fingolfin** [comment]
From my perspective this is fixed. Yes, `convert(GapObj, 1)` is problematic in that it doesn't return a `GapObj` but that's for now not a serious issue.
