### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by thofma** [oscar-system/GAP.jl#553]
This is with the master branch of Oscar:
```
julia> using Oscar
#I  Getting PackageInfo URLs...
#I  Created directory /home/bla/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/pkg/
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/ferret/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/gap-packages/ferret/releases/download/v1.0.3/ferret-1.0.3.tar.gz ...
#I  Saved archive to /tmp/tm7BNXth/ferret-1.0.3.tar.gz
#I  Extracting to /home/bla/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/pkg/ferret-1.0.3 ...
#I  Checking dependencies for ferret...
#I    GAPDoc >= 1.5: true
#I  Running compilation script on /home/bla/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/pkg/ferret-1.0.3 ...
#W dlopen() error: /home/bla/julia/julia-1.5.1/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/bla/.julia/pa\
ckages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/pkg/ferret-1.0.3/bin/x86_64-pc-linux-gnu-julia64-kv7-v1.5/ferret.so)
ERROR: InitError: Error thrown by GAP: Error, module '/home/bla/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/pkg/ferret-1.0.3/bin/x86_64-pc-linux-gnu-julia64-kv7-v1.5/ferret.so' not found
```

```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```
@fingolfin @ThomasBreuer

**Comment by fingolfin** [comment]
His looks like the classical bug of "Julia bundles its own copy of the standard C++ library which is older than what the C++ compiler uses, so any C++ compilation fails". And here it tries to compile ferret, which uses C++...

The quickest solution (if you just want to get things to work) is to delete the copy of the C++ library bundled with Julia, it'll happily use the newer one which is installed system wide.

I am actually not sure how else to deal with this properly; I am pretty sure Polymake will run into similar issues, as it also compilers C++ code on the user's system, and there is no way avoiding it there (for GAP.jl, at least in theory we could "move everything into JLLs", though in practice it's not that easy either).

I think we reported this to the Julia folks before, but AFAIK they made no move to improve the situation on their side.

**Comment by thofma** [comment]
I see, thanks. I thought that https://github.com/JuliaLang/julia/pull/37955 would give a possible solution. I probably misunderstood something.

**Comment by fingolfin** [comment]
I wasn't aware if that one, sounds great if it works in the end. However, it would only reduce the impact of the issue, not remove it completely. But it'd still be an improvement.

**Comment by fingolfin** [comment]
Hopefully https://github.com/JuliaLang/julia/pull/46976 will take care of this for good.
