### ISSUE TITLE
Add `force=true` option to `GAP.Packages.install` and `GAP.Packages.remove`?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#567]
So that they don't produce an error if the package is already installed resp. is not installed?

**Comment by ThomasBreuer** [comment]
@fingolfin I do not understand this.
When I call `GAP.Packages.remove("not_installed")` or `GAP.Packages.remove("not_installed", interactive = false)` then I get `false` (after some messages).
In which situations do you run into an error?

**Comment by fingolfin** [comment]
I can't recall what this was really about, and so i think I was confused when I wrote that. Let's close it, I can always reopen if I remember what this was about (and it turns out not to be nonsense)
