### ISSUE TITLE
Broken link to JuliaInterface doc

### ISSUE THREAD

**Issue by ssiccha** [oscar-system/GAP.jl#588]
In `docs/src/index.md` there is a link to "manual of the GAP package JuliaInterface" `https://oscar-system.github.io/GAP.jl/dev/GAP_ref(JuliaInterface:Title%20page)`. For me that link yields a 404 Page not found error.

**Comment by fingolfin** [comment]
This is related to issue #356: we currently don't upload the JuliaInterface documentation to `gh-pages`; this is a pure engineering issue, i.e., someone needs to sit down and figure out how to fix that (it must be coordinated with the upload of the generated Julia documentation)

**Comment by ThomasBreuer** [comment]
The file `docs/src/index.md` is just the *source* of the GAP.jl documentation. Almost all links in this file are computed when the documentation gets processed. The final documentation, if it has been built, can be found in `docs/build`.

Concerning the link from the GAP.jl documentation to the `JuliaInterface` manual, the situation is as explained by @fingolfin.
