### ISSUE TITLE
Calling GapObj on Tuples yields Arrays

### ISSUE THREAD

**Issue by SyxP** [oscar-system/GAP.jl#596]
See attached code.

```
julia> GAP.evalstr("(1,2,3)")
GAP: (1,2,3)

julia> GapObj((1,2,3))
GAP: [ 1, 2, 3 ]
```

**Comment by fingolfin** [comment]
There are no tuples in GAP.

Your first input returns a GAP permutation.

Your second input returns a GAP list (roughly corresponds to a Julia Vector/Array).

**Comment by fingolfin** [comment]
I don't see an issue here, so I am going to close this. But feel free to provide additional information, then we can reopen.

**Comment by SyxP** [comment]
Ah the difficulty I faced was that when I tried to replicate the GAP code `Group((1,2,3))`, I tried `GAP.Globals.Group(GapObj((1,2,3)))` which didn't work, but required `GAP.Globals.Group(Gap.evalstr("(1,2,3)")`, perhaps not a bug but perhaps should be at least noted somewhere. I think this is likely the first things people might try.
