### ISSUE TITLE
Fix doctests failures due to whitespace changes in Julia nightly

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#601]
They made printing of various things subjectively nicer, but it causes silly diffs in our doctests, e.g.
- `Dict{Symbol,Int64}` -> `Dict{Symbol, Int64}`
- `Dict{Symbol,Any}` -> `Dict{Symbol, Any}`
- `Dict{Symbol,Array{Int64,1}` -> ` Dict{Symbol, Vector{Int64}}`
- `StepRange{Int8,Int8}` -> `StepRange{Int8, Int8}`

Hopefully we can address those with additional doctest filters.

**Comment by ThomasBreuer** [comment]
I will create a pull request for dealing with these cases via doctestfilters.
