### ISSUE TITLE
How to get on the Julia side a GAP object wrapping a Julia function?

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#629]
I ran into this question in the context of issue oscar-system/Oscar.jl/issues/108:

In a GAP session, I can fetch the Julia function `sqrt` via `JuliaFunction( "sqrt" )`; in fact, this yields a GAP object in the filter `IsFunction`.
In a Julia session, this object would be interesting in situations where a GAP operation gets called which expects one of its arguments to have the filter `IsFunction`. However, `GAP.Globals.JuliaFunction(g"sqrt")` yields not the wrapped GAP object but the Julia function itself, which is not in GAP's `IsFunction`.

How can I construct the `IsFunction` object on the Julia side?

(The above description should become part of the documentation for GAP.jl and JuliaInterface.)

**Comment by fingolfin** [comment]
You can use NewJuliaFunc, I think (soon to be renamed to WrapJuliaFunc)

**Comment by fingolfin** [comment]
See also PR #631.
