### ISSUE TITLE
Error during tests with GAP

### ISSUE THREAD

**Issue by iliailmer** [oscar-system/GAP.jl#635]
We have a package that uses Singular and Gap as dependencies. During the testing stage of CI in github actions we encountered this error:
```
ERROR: ArgumentError: Package Pkg not found in current path:
- Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
ERROR: LoadError: failed process: Process(`/opt/hostedtoolcache/julia/1.5.3/x64/bin/julia -Cnative -J/opt/hostedtoolcache/julia/1.5.3/x64/lib/julia/sys.so --depwarn=yes --check-bounds=yes -O0 -g1 --code-coverage=user --color=yes --startup-file=no --startup-file=no --project=/home/runner/.julia/packages/GAP/Gc53G/gaproot/v1.5 -e 'using Pkg; Pkg.develop(PackageSpec(path="../..")); Pkg.resolve()'`, ProcessExited(1)) [1]
```

this is running on Ubuntu-latest with Julia-1.5.3.
What could be the issue here? this does not occur locally. 

Gap version used during this CI are as follows (from manifest.toml).
```
  [c863536a] GAP v0.5.2
  [5cd7a574] GAP_jll v400.1100.1+0
  [de1ad85e] GAP_lib_jll v400.1100.0+0
```

**Comment by fingolfin** [comment]
That's bizarre (note the nonsensical suggestion to use Pkg to install Pkg...). Do you have a link to a complete build log perhaps?

**Comment by iliailmer** [comment]
@fingolfin Here is one version: https://github.com/iliailmer/SIAN-Julia/runs/2123878422?check_suite_focus=true
>  the nonsensical suggestion to use Pkg to install Pkg...
this is indeed strange, and manually running the suggested fix `import Pkg; Pkg.add("Pkg")` does not help.

**Comment by iliailmer** [comment]
The issue stems from this code part:
https://github.com/oscar-system/GAP.jl/blob/398b6f3ae3f4104129140ff59ab21c330c5d0057/src/setup.jl#L225

**Comment by fingolfin** [comment]
Sure, that was clear already. It remains unclear what causes the issue, and why it doesn't affect e.g. the GAP.jl and Oscar.jl CI test suites which also run on Ubuntu in GitHub actions

**Comment by ThomasBreuer** [comment]
Just to make sure that the problem is not caused by [a wrong value of LOAD_PATH](https://discourse.julialang.org/t/problem-with-pkg-cannot-be-found-in-current-path/26492):
I get the abovementioned error message when I set the environment variable `JULIA_LOAD_PATH` to a wrong value.

**Comment by iliailmer** [comment]
@ThomasBreuer if I am running it on github actions, here is the output `Base.load_path()` in the `runtests.jl`
```
["/tmp/jl_3k65pn/Project.toml"]
```

and here is what `LOAD_PATH` and `Base.load_path()` just before the test (called via shell command as `julia -E LOAD_PATH`):
```
$ julia -E "LOAD_PATH"
["@", "@v#.#", "@stdlib"]
```

```
$ julia -E "Base.load_path()"
 ["/home/runner/.julia/environments/v1.5/Project.toml", "/opt/hostedtoolcache/julia/1.5.3/x64/share/julia/stdlib/v1.5"]
```

**Comment by fingolfin** [comment]
@iliailmer I see that you submitted an issue to julia-actions/julia-runtest -- note that we are also using that, for GAP.jl and for Oscar.jl, and there we see no such issues.

**Comment by iliailmer** [comment]
@fingolfin thank you for letting me know. I did try their suggestion and the test is still failing at the `[ Info: Generating custom Julia project ...` stage. What is strange is that locally everything runs normally.

**Comment by iliailmer** [comment]
Hi, @fingolfin are there any updates on this issue?

**Comment by fingolfin** [comment]
No. We cannot reproduce the issue locally nor in a similar CI setup. With zero leads, there's no way for us to debug this.

So this leaves as only option to replace the offending code; but this is a feature we and some of our users rely on, so we can't just remove it. See also issue #611 for some thoughts on that.

However, as I said, it works for us right now, and at least I am busy with many other things, so resolving your issue unfortunately is no priority right now, sorry

**Comment by fingolfin** [comment]
@iliailmer I just released GAP.jl 0.6.1. Just wondering if this issue still happens for you with it...?

**Comment by iliailmer** [comment]
Hey, thanks for reaching out. When using the latest Julia version, tests seem to work fine. I will close the issue with this comment, sorry for not doing this earlier.
