### ISSUE TITLE
Broken on recent master

### ISSUE THREAD

**Issue by thofma** [oscar-system/GAP.jl#646]
With a julia build from today (https://github.com/JuliaLang/julia/commit/e3adc399e6bf69d0801c243f254ff8624f50d3c4) I get:
```julia
/tmpbig/bla/julia/usr/bin/julia: symbol lookup error: /tmpbig/bla/artifacts/950ff4d50dce8d40bb
47ca0431b697dcc9eae5c4/lib/libgap.so: undefined symbol: jl_init__threading
ERROR: LoadError: Failed to precompile GAP [c863536a-3901-11e9-33e7-d5cd0df7b904] to /tmpbig/bla/co
mpiled/v1.7/GAP/jl_nPxktU.
```

**Comment by ThomasBreuer** [comment]
I can reproduce this behaviour on my notebook.

**Comment by fingolfin** [comment]
Indeed https://github.com/JuliaLang/julia/commit/c556bb9e53779994c88587e8b24e698b7cf38527 is the culprit -- they just broke ABI compatibility with that once again. I've commented accordingly at https://github.com/JuliaLang/julia/issues/40246#issuecomment-831819816

**Comment by fingolfin** [comment]
See also https://github.com/JuliaLang/julia/issues/40730 and https://github.com/JuliaLang/julia/pull/40851

**Comment by fingolfin** [comment]
This is resolved now
