### ISSUE TITLE
Override GAP function `PKGMAN_DownloadURL` to use Julia for downloading?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#692]
The problem with `PKGMAN_DownloadURL` is that it does different things for different systems (e.g. it might use curl or wget or curlInterface or maybe something else), and if those run into errors, it can be hard to reproduce and debug. If we instead use Julia's `download()` we should get more consistent behavior. That is, assuming `download` can do what we need.

**Comment by fingolfin** [comment]
Actually, we probably should just use https://github.com/JuliaLang/Downloads.jl instead (`Base.download()` is deprecated in favor of it)

**Comment by lgoe-ac** [comment]
I'll have a shot at this
