### ISSUE TITLE
JuliaInterface manual: reference to `\[\]` and `\(\)` glitching due to MathJax

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#786]
Looking at [this part of the JuliaInterface manual](https://oscar-system.github.io/GAP.jl/dev/assets/html/JuliaInterface/chap2_mj.html#X821EFEF1843BA0F1) I see this:
<img width="689" alt="Screenshot 2022-02-15 at 00 57 31" src="https://user-images.githubusercontent.com/241512/153966847-d333cf94-66d3-428e-af11-8915acd5a11b.png">

This is caused by MathJax thinking this is an attempt to render a Math formula, and performing a corresponding substitution.

I am not sure whether we can do something about this (other than a hack were we run a script over the generated HTML to "fix" it), it may have to be addressed in GAPDoc?!

**Comment by frankluebeck** [comment]
Thanks for this example.
This is now fixed in [GAPDoc](https://github.com/frankluebeck/GAPDoc).

**Comment by fingolfin** [comment]
Great, thanks! Could you make anew GAPDoc release with this fix in?
