### ISSUE TITLE
doc: table of contents unsorted

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#787]
The "Table of contents" displayed on https://oscar-system.github.io/GAP.jl/dev/ in the body (not the navbar) is not sorted the way I'd like it to be sorted (namely the same as in the nav bar). Instead it seems to be sorted by filename?

Not sure what we can do about this... perhaps we should just drop that ToC, it's not *that* useful?

**Comment by ThomasBreuer** [comment]
The table of contents in the navigation bar is generated from the `pages` list in the `makedocs` call.
The table of contents in the introductory page is generated using Documenter.jl's `@contents` block;
this block admits a `Pages` list, the default is apparently the alphabetically sorted list of files.

We can enter the same list in the `@contents` block as in the `makedocs` call, or we can omit the `@contents` block.

(In the former case, we should make sure that the explicit list is stored just in *one* place, and I found no better way to achieve this than to put the list into a new file `docs/src/files.jl` and then to load its contents with `evalfile(joinpath(dirname(pathof(GAP)), "../docs/src/files.jl"))` in both places.)
