### ISSUE TITLE
New error on julia master?

### ISSUE THREAD

**Issue by thofma** [oscar-system/GAP.jl#789]
https://github.com/oscar-system/Oscar.jl/runs/5305495803?check_suite_focus=true:

```
[ Info: Set up gaproot at /home/runner/.julia/packages/GAP/lK1LP/gaproot/v1.9
ERROR: LoadError: UndefVarError: find_artifact_dir not defined
Stacktrace:
 [1] getproperty
   @ ./Base.jl:31 [inlined]
 [2] regenerate_gaproot(gaproot_mutable::String)
   @ GAP.Setup ~/.julia/packages/GAP/lK1LP/src/setup.jl:93
 [3] top-level scope
   @ ~/.julia/packages/GAP/lK1LP/src/GAP.jl:26
 [4] include
   @ ./Base.jl:422 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1399
 [6] top-level scope
   @ stdin:1
in expression starting at /home/runner/.julia/packages/GAP/lK1LP/src/GAP.jl:1
in expression starting at stdin:1
```

Feel free to close this issue if this is known :)

**Comment by fingolfin** [comment]
This is because julia nightly is now 1.9, all our JLLs using libjulia need to rebuilt with 1.9 binaries. I already updated the JLLs for libjulia, libcxxwrap and GAP, but not those for singular and polymake. I also did not yet have time to switch GAP.jl to the new JLL

**Comment by thofma** [comment]
Ah ok, the error message is quite confusing as the symbol `find_artifact_dir` seems to not be defined in this case.

**Comment by fingolfin** [comment]
Indeed. I think we could do better (in each of the GAP/Polymake/Singular packages) by adding an explicit check `GAP_jll.is_available() || error(...)` in a suitable place,

**Comment by fingolfin** [comment]
Should be resolved now
