### ISSUE TITLE
lib/debug.g cannot be loaded

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#796]
GAP's `lib/debug.g` is not loaded into the GAP session by default. When I try to load it using `ReadLib` (after entering a GAP session from Julia via `GAP.prompt()`), I get an error message because some files in GAP's `etc` directory are needed but the artifact used by GAP.jl does not have an `etc` directory.
Do we want to leave out the `etc` directory from the artifact?
(Currently `DirectoriesLibrary("etc")` finds the `etc` subdirectory of GAP.jl. Perhaps it is dangerous to have `etc` directories with different meanings in the GAP root paths, this may be a reason for leaving out GAP's original `etc`?)
If yes then we should change `lib/debug.g` in order to give a better error message.

I noticed this when I tried to inspect the problem from #795.

**Comment by fingolfin** [comment]
We should update GAP_jll or GAP_lib_jll to include GAP's `etc` directory. Also GAP's `make install` should probably install it.
