### ISSUE TITLE
Print about xgap package when loading OSCAR

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/GAP.jl#831]
When I do `using Oscar` I get
```
#I  You may wish to install the xgap package
#I  and enjoy the graphic capabilities of SONATA.
```
after the copyright message.

**Comment by fingolfin** [comment]
Thanks for filing the issue, @joschmitt !

Thanks to @ThomasBreuer for tracking it down; turns out it is a problem in Oscar (and perhaps GAP)
