### ISSUE TITLE
Documentation: add some non-trivial examples for how to use GAP.jl

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#838]
That is, perhaps show some basic GAP code, then show how the "equivalent" Julia code would like.

E.g. today I was asked how to translate this GAP code (it uses the LINS package by Friedrich Robers -- for an example in the manual, it of course shouldn't use anything not shipped with GAP by default):
```gap
f := FreeGroup("a", "b");
g := f / [f.1^2, f.2^l, (f.1*f.2)^m];
a := g.1;
b := g.2;
gr := LowIndexNormalSubgroupsSearchForAll(g, N);
ns := ComputedNormalSubgroups(gr);
```
I proposed this translation:
```julia
f = GAP.Globals.FreeGroup(g"a", g"b")
g = f / GapObj([f.:1^2, f.:2^l, (f.:1*f.:2)^m])
a = g.:1
b = g.:2
gr = GAP.Globals.LowIndexNormalSubgroupsSearchForAll(g, N)
ns = GAP.Globals.ComputedNormalSubgroups(gr)
```

**Comment by ThomasBreuer** [comment]
What about the "Rubik's Cube" example at https://www.gap-system.org/Doc/Examples/rubik.html?
There is a translation to Julia using GAP.jl (by Reimer, if I remember well), as a Jupyter notebook.
