### ISSUE TITLE
gap-packages fails to unpack on Windows (WSL)

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/GAP.jl#850]
Unpacking the gap package tarball on Windows (inside WSL) currently fails with `Invalid argument` because of a file with an invalid character for a NTFS file system. This currently breaks installation of Oscar.

The current `packages-v4.12.1.tar.gz` contains `hap/lib/Functors/:q` which was probably committed by accident and removed in HAP 1.48 and 1.49 but this is not available in the gap packages tarball yet. (4.12.2 also lists HAP 1.47) 

cc: @Sequenzer

**Comment by fingolfin** [comment]
Since the problem also affects the 4.12.2 tarball, I'll have to make a new stable snapshot. It's not hard to do but it means I'll need a bit more time. Should come soon, though.
