### ISSUE TITLE
"Compiling JuliaInterface" displayed every time when loading GAP.jl

### ISSUE THREAD

**Issue by zickgraf** [oscar-system/GAP.jl#923]
Since 38af454942a1924b39f30f00a8a64622dd06ce32, `using GAP` always displays "Compiling JuliaInterface":
```
[ Info: Compiling JuliaInterface ...
 ┌───────┐   GAP 4.12.2 of 2022-12-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-julia1.11-64-kv8
 Configuration:  gmp 6.2.1, Julia GC, Julia 1.11.0-DEV, readline
 Loading the library and packages ...
 Packages:   Alnuth 3.2.1, AutPGrp 1.11, CRISP 1.4.6, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.6, IO 4.8.1, IRREDSOL 1.4.4, JuliaInterface 0.9.7, LAGUNA 3.9.5, 
             Polycyclic 2.16, PrimGrp 3.4.3, ResClasses 4.7.3, SmallGrp 1.5.1, Sophus 1.27, TransGrp 3.6.3, utils 0.81
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

Is this intended and a permanent change?

Background: This currently breaks our CI with GAP.jl master because the line "[ Info: Compiling JuliaInterface ..." suddenly appears in outputs. Of course there are various solutions (officially including the line in the expected output, filtering out the line etc.). But before I implement those I wanted to ask if this change will be permanent because I suspect/hope that it will vanish with the next rebuild of "GAP_pkg_juliainterface_jll" anyway :-)

**Comment by ThomasBreuer** [comment]
As far as I understand, this message appears whenever the `pkg/JuliaInterface/src` directory of GAP.jl differs from the corresponding directory of the JuliaInterface jll in `.julia/artifacts`.
The mentioned commit introduced such a difference.

**Comment by fingolfin** [comment]
This is a known consequence how updating JLLs work for us. This will soon go away again (and come back again temporarily whenever we make changes to the C code in this repo)

**Comment by zickgraf** [comment]
I see, that's about what I suspected. Thanks @ThomasBreuer and @fingolfin for the details!

**Comment by fingolfin** [comment]
See #924
