### ISSUE TITLE
intended behavior of `ConvertedToJulia`?

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#94]
Currently `ConvertedToJulia` seems to return its input when no corresponding Julia object exists.
For example, `ConvertedToJulia( Group( () ) )` returns the given GAP group.

In `JuliaInterface/src/JuliaInterface.c`,
`Func_ConvertedToJulia` calls `Func_ConvertedToJulia_internal`
and returns `Fail` if the result is zero, but the result is never zero.

**Comment by fingolfin** [comment]
See also issue #28 were I ask similar related questions

**Comment by sebasguts** [comment]
I think this issue does not really apply to our current code anymore, as we only have `GapToJulia` and `JuliaToGAP` left, right?

**Comment by fingolfin** [comment]
`ConvertedToJulia` does not exist anymore; but it is still referenced in pkg/JuliaExperimental/ipynb/GAPJulia_Singular_blog.ipynb

@ThomasBreuer Can this issue be closed?
