### ISSUE TITLE
processing the documentation is broken with Documenter.jl v1.0.1

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#943]
Documenter.jl v1.0 seems to have interesting new features (see oscar-system/Oscar.jl/issues/588).
However, first of all it does no longer work with our extension that deals with external references to GAP manuals.
Apparently `Documenter.Documents` does no longer exist.

**Comment by fingolfin** [comment]
Indeed, but we just use `Documenter.Documents.Document` which has become `Documenter.Document` (reading the latter hurts slightly less than reading the former :-)

**Comment by fingolfin** [comment]
Here is how we deal with it [in Oscar.jl](https://github.com/oscar-system/Oscar.jl/blob/199fd64e0d04174b96b44eca4aee81d83dcb917f/src/utils/docs.jl#L42-L46):
```julia
  if isdefined(Main.Documenter, :Document)
    Document = Main.Documenter.Document
  else
    Document = Main.Documenter.Documents.Document
  end
```
(In our case we can drop the `Main.` prefix)

**Comment by ThomasBreuer** [comment]
Thanks.
We use also `Documenter.Documents.walk`. (I guess this is now `Documenter.walk_navpages`.)

Anyhow, the warnings which we got up to now in the treatment of external references are now errors.
I will have to revise this extension.

(As far as I understand, the new feature of Documenter.jl concerning links to other repositories of Julia packages cannot help us, since we want links to GAP manuals.)
