### ISSUE TITLE
REPL completions again broken in Julia nightly

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#962]
... according to a local test run:
```
Test Summary: | Pass  Total  Time
help          |   20     20  2.8s
REPL completions: Test Failed at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:25
  Expression: length(c) == 2
   Evaluated: 0 == 2

Stacktrace:
 [1] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:25 [inlined]
 [3] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
 [4] top-level scope
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:15
REPL completions: Test Failed at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:26
  Expression: "IsIndecomposable" in c
   Evaluated: "IsIndecomposable" in String[]

Stacktrace:
 [1] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:26 [inlined]
 [3] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
 [4] top-level scope
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:15
REPL completions: Test Failed at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:33
  Expression: length(c) == 1
   Evaluated: 0 == 1

Stacktrace:
 [1] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:33 [inlined]
 [3] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
 [4] top-level scope
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:15
REPL completions: Test Failed at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:34
  Expression: "IsIndecomposable" in c
   Evaluated: "IsIndecomposable" in String[]

Stacktrace:
 [1] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:679 [inlined]
 [2] macro expansion
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:34 [inlined]
 [3] macro expansion
   @ ~/Projekte/Julia/julia.master/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
 [4] top-level scope
   @ ~/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:15
Test Summary:    | Pass  Fail  Total  Time
REPL completions |   10     4     14  0.9s
ERROR: LoadError: Some tests did not pass: 10 passed, 4 failed, 0 errored, 0 broken.
in expression starting at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/replcompletions.jl:12
in expression starting at /Users/mhorn/Projekte/OSCAR/GAP.jl/test/runtests.jl:16
ERROR: Package GAP errored during testing
```

Two things we should do
- [ ] ensure we run this test as part of CI -- that probably means running some or all tests also with code coverage turned off
- [ ] fix the REPL completion in Julia 1.11

**Comment by fingolfin** [comment]
I used `git bisect` to narrow this down to https://github.com/JuliaLang/julia/commit/0d544cc5f23bbe7cf5d8775f763edc3d2c249a09 by @aviatesk

Based on this, I guessed that maybe this would resolve the issue, and indeed it does:
```
diff --git a/src/ccalls.jl b/src/ccalls.jl
index 3d71f34..5863550 100644
--- a/src/ccalls.jl
+++ b/src/ccalls.jl
@@ -6,7 +6,7 @@ import Base: getproperty, hasproperty, setproperty!, propertynames
 #
 # low-level GAP -> Julia conversion
 #
-Compat.@assume_effects :effect_free :terminates_globally function _GAP_TO_JULIA(ptr::Ptr{Cvoid})
+Compat.@assume_effects :effect_free :terminates_globally :noub function _GAP_TO_JULIA(ptr::Ptr{Cvoid})
     ptr == C_NULL && return nothing
     # convert immediate ints and FFEs directly, to avoid (un)boxing
     as_int = reinterpret(Int, ptr)
@@ -157,7 +157,7 @@ end
 
 # Retrieve the value of a global GAP variable given its name. This function
 # returns a raw Ptr value, and should only be called by plumbing code.
-Compat.@assume_effects :effect_free :terminates_globally function _ValueGlobalVariable(name::Union{AbstractString,Symbol})
+Compat.@assume_effects :effect_free :terminates_globally :noub function _ValueGlobalVariable(name::Union{AbstractString,Symbol})
     return ccall((:GAP_ValueGlobalVariable, libgap), Ptr{Cvoid}, (Cstring,), name)
 end
 
```


Unfortunately, there are several issues. First off, this patch works in Julia >=1.11 but not in 1.10 which does not know an effect named `:ub`. I am actually not sure how I could rewrite this code to apply different effects for different Julia versions without duplicating the entire function?

For `_GAP_TO_JULIA` this could perhaps be worked around by using the `:foldable` effect, which combined `:effect_free`, `:terminates_globally`, `:noub` and `:consistent` -- and which is supported by Julia 1.10. As far as I understand, the use of `:consistent` for it would be correct.

Unfortunately I don't think it would be correct for `_ValueGlobalVariable`, as that function essentially takes a given string or symbol and then looks up whatever value is stored under that name, and that can change over time.

But at least `_ValueGlobalVariable` is very short, so one can get away with some code duplication... The result is in https://github.com/oscar-system/GAP.jl/pull/969


Another point I am uncertain about: is the application of `:noub` actually correct? The documentation says:

> The `:noub` setting asserts that the method will not execute any undefined behavior
(for any input). 

But `_GAP_TO_JULIA` takes a `Ptr`, and if an invalid pointer is fed to it, it might e.g. segfault, or produce garbage output. Granted, in all places we actually do call it, this is impossible (modulo a bug or memory corruption). But still... 


Finally I wonder if this is the only way to restore REPL tab completion for e.g. `GAP.Globals.MTX.S` in GAP.jl

**Comment by aviatesk** [comment]
You can use `@assume_effects :foldable !:consistent` setting to allow TAB completions without giving the incorrect `:consistent` assumption. Otherwise you will need to do something like:
```julia
@static if VERSION > v"xxx"
macro my_assume_effects(ex)
    ...
end
else
macro my_assume_effects(ex)
    ...
end
end
```

**Comment by fingolfin** [comment]
Thanks @aviatesk I wasn't aware that one can negate like that, it seems to work like a charm :-)
