### ISSUE TITLE
`GapObj` vs `julia_to_gap`

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#990]
The use of `GapObj` as a constructor is getting more and more popular.
Currently the implementation provides just `GapObj(obj, recursive)`, and `GapObj(obj; recursive = false)`,
and delegates to the three argument version `julia_to_gap(obj, IdDict(); recursive)`.

This way, calling `GapObj` with one argument often runs via `julia_to_gap(obj, IdDict(); recursive)` into the default method of `julia_to_gap` that discards the last two arguments.

Can't we use `GapObj` and `julia_to_gap` as synonyms?
Then this detour would be avoided, and the special one-argument method would be called directly.

**Comment by fingolfin** [comment]
How does this relate to issue #1025 which has basically the same title?

**Comment by fingolfin** [comment]
These days `julia_to_gap` and `GapObj` both delegate to `GapObj_internal` and so are essentially synonyms as suggested here, so I think we can close this now.
